define emi_name = _("Emi")
define ingram_name = _("Ingram")
define kai_name = _("Kai")
define annelise_name = _("Annelise")
define akira_name = _("Akira")

define emi = Character(emi_name, color="#ffbcca")
define ingram = Character(ingram_name, color="#9fe7ff")
define kai = Character(kai_name, color="#fad5af")
define akira = Character(akira_name, color="#c7f5c5")
define annelise = Character(annelise_name, color="#fff0b1")

define uk_nar = Character("", what_slow_cps=30)
define uk_generic = Character("?????", color="#ffffff")
define uk_emi = Character("?????", color="#ffbcca")
define uk_ingram = Character("?????", color="#9fe7ff")
define uk_kai = Character("?????", color="#fad5af")
define uk_akira = Character("?????", color="#c7f5c5")
define uk_annelise = Character("?????", color="#fff0b1")