define emi_name = _("Emi")
define ingram_name = _("Ingram")
define kai_name = _("Kai")
define annelise_name = _("Annelise")
define akira_name = _("Akira")

define emi = Character(emi_name, color="#ffbcca")
define ingram = Character(ingram_name, color="#9fe7ff")
define kai = Character(kai_name, color="#fad5af")
define akira = Character(akira_name, color="#c7f5c5")
define annelise = Character(annelise_name, color="#fff0b1")

define unknown_nar = Character("", what_slow_cps=30)
define unknown_generic = Character("?????", color="#ffffff")
define unknown_e = Character("?????", color="#ffbcca")
define unknown_i = Character("?????", color="#9fe7ff")
define unknown_k = Character("?????", color="#fad5af")
define unknown_ak = Character("?????", color="#c7f5c5")
define unknown_an = Character("?????", color="#fff0b1")