label afternoon_chat:
    emi talk "You know what, you have a point! It can't hurt to take a little break."
    narrator base "I plop down on the seat across from Akira, sinking into the comfortable cushion on the chair. He smiles, pleased that I've accepted his invitation."
    akira "I'm glad to hear that. It's always nice to have some company on a day like today."
    akira "It's also important to take breaks from time to time, don't you think?"
    narrator "His easygoing demeanor puts me at ease, and I find myself relaxing in no time. I return his smile, feeling a sense of warmth at his words."
    akira "So how's everything going around the cafe? You're fairly new, yet you're already working so diligently."
    emi talk "Oh, I'm learning a lot from Ingram! But I've still got a long way to go before I get to whip up some fancy desserts though."
    akira base "Is that so? You seem so excited to get baking, is there a particular reason?"
    emi talk "Have you seen those cakes in the display case? They look absolutely stunning!"
    emi "Wouldn't it be really cool if I could do that myself? I'd love to create something so pretty-looking."
    emi "There's also something special about seeing people enjoy what I've made with my own two hands."
    narrator base "Akira chuckles softly, his laughter like a melody that fills the air. As I speak, I notice a spark of recognition in his eyes, as if he understands the satisfaction of pursuing one's passions."
    narrator "Leaning forward, he rests his chin on his hand, his gaze full of intrigue and curiosity."
    akira "That's admirable. Both precision and skill are essential to creating such complicated desserts, so it's good to hone them through practice."
    akira "As a regular, I'd be honoured to taste your creations someday."
    narrator "I feel a surge of pride at his compliment, grateful for his recognition."
    emi talk "Thank you, I'm touched that you think so highly of me."
    akira base "Of course. Only through diligence and perseverance can you expect to reap meaningful results."
    narrator "I stare as Akira takes another sip of his espresso."
    narrator "His calm demeanor exudes a sense of confidence that is both comforting and inspiring. He seems so at ease, blending seamlessly into his surroundings."
    emi "(I wonder if he's been here for a while. . .)"
    akira "How are you finding Nobaros? Adjusting well?"
    narrator "His question catches me off guard, as if he read my mind."
    emi talk "Eh? Ah, I mean, it's. . . different. I'm still trying to get my bearings to be honest. But I do appreciate how tranquil this place is. I think I'll slowly be able to adjust."
    akira base "I understand. When I first arrived, it was quite overwhelming. Nobaros was unlike anything I've experienced before. But I've found it to be quite nice, a place of introspection and growth if you will."
    emi talk "It's reassuring to hear that. What was your first impression of Nobaros, if you don't mind me asking?"
    akira base "Frankly speaking, I was in disbelief. The concept of being in a place like this, where people who have passed on or are close to it coexist, was unfathomable to me."
    akira "Walking around here with that in mind was a strange feeling. And even more so when I realized that included me."
    akira "But over time, I've come to appreciate the peace it offers. It provided an opportunity to slow down and reflect on a lot of things."
    akira "Things that I would've never stopped to think about in reality."
    emi "(No wonder he seems so well-adjusted. . .)"
    narrator "As Akira gracefully savours another sip of his espresso, I couldn't help but wonder about his life before Nobaros. What kind of life did he lead in the real world?"
    narrator "With a fluid motion, he finishes the drink and extends the empty cup to me."
    narrator "Rising from his seat, he stretches languidly, a sigh of satisfaction escaping his lips. He looks content, as if our conversation has left him refreshed."
    akira "Well then, I've kept you from your duties long enough. The sun has made me drowsy, so I think I'll take a stroll to wake myself up."
    akira "Thanks for entertaining me, it's been a pleasure."
    akira "Good luck with your shift."
    emi talk "Thank you! Enjoy your walk."
    hide akira with dissolve
    narrator base "I watch as Akira leaves, a sense of contentment washing over me."
    narrator "As I hold his empty cup, I feel a tinge in my chest, part of me wishing that there was more time to chat with him."
    narrator "I sigh softly, knowing that duty calls. {w=0.2}But I'm also content, happy with the choice I made."
    emi "(Let's quickly finish up here and return the rags.)"
    return
