label cafe_duties:
    narrator base "With a resigned sigh, I shake my head, acknowledging that my chores should take priority."
    narrator "If I slack off now, there's a chance that I wouldn't be able to finish them all in time."
    emi talk "Sorry, I would love to, but I'll have to take a rain check. There's a lot of work I need to focus on before the day ends."
    akira base "I see. I understand, no need to apologize. I admire your work ethic."
    narrator "Akira gracefully lifts the cup to his lips, savouring the last sip of his espresso."
    narrator "With a fluid motion, he finishes the drink and extends the empty cup to me. He stretches leisurely, a long sigh escaping his lips."
    akira "Well then, I've stuck around for long enough now. The sun has made me drowsy, so I think I'll take a stroll to wake myself up."
    narrator "I watch as Akira stands up, a sense of regret creeping in."
    narrator "Despite running into each other twice now, I still don't know very much about him. I wish I had more time to chat with him, to learn about his experiences in Nobaros."
    narrator "As Akira makes his way to the door, he turns back and smiles at me."
    akira "It's been a pleasure, good luck with your shift."
    akira "Perhaps we can continue our conversation next time."
    emi ". . . !"
    emi talk "Yes, definitely! Have a good day, I'll see you at Yuugen House."
    hide akira with dissolve
    narrator base "His departure leaves me with a sense of missed opportunity, a feeling that maybe I should have taken him up on his offer and savoured the moment."
    narrator "I sigh softly, knowing that duty calls and I ultimately made the responsible choice."
    emi "(Next time, I'll definitely take the chance to converse with him properly!)"
    emi "(Let's quickly finish up here and return the rags.)"
    return