label twilight_stroll:
    emi  "(Let's just head up and chill in my room.)"
    narrator "Wrapping a towel around my damp hair, I head towards the stairs. The towel feels warm and snug on my head, and I fantasize about the sweet comfort of my bed."
    emi "(Oh, maybe now's a good time to check out Annelise's book recommendation. I should go knock on her door and ask to borrow it.)"
    emi "(What was the title again, Hearth. . .? )"
    emi "Woah-!"
    narrator "As I approach the stairs, I collide with something warm and solid, causing me to stumble over my own feet."
    narrator "A pair of hands grab my shoulders, helping me regain my footing as my towel falls to the ground."
    show akira with dissolve
    akira "Are you okay, Emi?"
    narrator "Startled, I look up to see Akira, his expression a mix of surprise and concern from the sudden impact."
    narrator "With a swift, fluid motion, he quickly bends down, picks up the towel and hands it back to me."
    akira "Sorry about that, I should've been more careful. Here's your towel."
    emi "Thanks, it's no problem. I wasn't paying attention either."
    narrator "I feel a flush of embarrassment creeping up my cheeks as I accept the towel from him. My fingers brush against his for a brief moment, and I quickly pull back, clutching the towel to my chest."
    akira "You know, this is the second time we've bumped into each other on the stairs now."
    emi "Oh, you're right! Haha, I guess it's part of the whole roommate experience. It'd be hard not to run into each other."
    narrator "Akira chuckles and I reciprocate, the tension easing from my shoulders. His expression softens slightly, a small smile tugging at the corners of his lips."
    emi "So, what are you up to right now? It's getting pretty late."
    narrator "Akira glances towards the door, his eyes reflecting a sparkle of excitement."
    akira "I was just about to head outside. I wanted to clear my mind and enjoy the night breeze for a bit."
    akira "The sky's clear tonight and there's supposed to be a full moon. It'd be a shame to pass up this opportunity."
    akira "Care to join me? It's nice to appreciate beautiful scenery with good company."
    emi "That sounds interesting, I'd be down to tag along! I'm curious to see if it's as pretty as you're making it out to be."
    akira "Trust me, you'll definitely enjoy it."
    emi "Ah, but my hair is still a bit damp and I'm in my pajamas. . ."
    akira "That's alright, I can wait for you to dry your hair. We also aren't going too far from the house, so it's fine to stay in your pajamas."
    akira "I do recommend throwing on an extra sweater though. Wouldn't want to risk you catching a cold."
    emi "Good call, I'll look for one before we head out. Be right back!"
    scene blank with bgwipe
    scene bedroom_evening with bgwipe
    narrator "I dart up the stairs to my room, leaving Akira to loiter around the common area. In a heartbeat, I frantically dry my hair and find something warm to wear."
    emi "(This looks okay, right. . .?)"
    emi "(Oh, whatever! It's just a walk anyways. Let's not keep him waiting.)"
    narrator "With a final glance in the mirror, I make my way back downstairs, feeling a mix of anticipation and excitement."
    scene blank with bgwipe
    scene forest_path with bgwipe
    show akira with dissolve
    narrator "Together, we head out into the night, trekking along a nearby trail that leads up a hill."
    narrator "The breeze feels cool against my skin, having been in a steaming hot bath not too long ago. For a moment, I feel thankful that I'm wearing an extra layer."
    narrator "As we walk, I catch a glimpse of the moon in all its glory, casting a silver glow over everything. With the faint smell of grass surrounding us, I feel a sense of peace wash over me."
    emi "I've never gone on a walk at night before. It's more relaxing than I imagined."
    akira "It's good that you came along. Nights like these are rare."
    akira "It's not often that you see a full moon. If you miss one, you need to wait about a month for the next one."
    emi "I see. Do you prefer nighttime, Akira?"
    akira "I suppose so. There's a subtle comfort in being out at night. You notice things that you normally wouldn't see in the daytime."
    akira "Without any distractions to bother me, this time of day also makes it easier to reflect and organize my thoughts."
    emi "That makes sense. It's a very different vibe for sure."
    emi "By the way, what's at the top of this hill? What kind of scenery are we going to see later?"
    akira "You'll see, it's a surprise."
    akira "Just make sure to watch your step. The trail does get a bit rockier as we continue on."
    narrator "We both fall silent as we continue up the hillside trail, with Akira leading the way."
    narrator "The soft rustling of our footsteps and quiet chirping of crickets create a melodious soundscape, a lovely symphony that seems to never end."
    scene blank with bgwipe
    scene firefly with bgwipe
    narrator "As we near the top, the darkness around us gradually dissolves, replaced by a golden glow. I gasp in astonishment as the trail opens up into a secluded clearing."
    narrator "Tall blades of grass flourish, their tips brushing against my legs like whispers of silk as the scent of wildflowers linger."
    narrator "Amongst the grass are thousands of fireflies, their lights like tiny stars slowly dancing about."
    narrator "As I step forward to explore the clearing, I look up at the sky where the dense forestry recedes, staring into the endless expanse of starry sky."
    show akira with dissolve
    emi "It's. . . it's breathtaking. I don't know what to say."
    akira "I'm glad the weather's warm enough for them to come out. Usually, you'll only find fireflies during summer evenings."
    akira "It's a shame that we can't stargaze tonight because of the full moon though. The brightness makes it hard to see the stars."
    narrator "I turn to face Akira, shaking my head with a content smile spreading across my face."
    emi "That's okay, we can go stargazing some other time. Besides, I really like the current view!"
    emi "Look at all the fireflies, aren't they beautiful?"
    narrator "Akira's lips form a gentle smile, and he nods in agreement. We stand there for a moment, taking in the scene around us."
    emi "Seeing them up close is so mesmerizing. It feels like a scene right out of a book."
    akira "Fireflies are fascinating creatures, actually. Without needing any batteries or electricity, they manage to create a bright, tender glow."
    emi "Huh, I never thought about that. How do they light up?"
    akira "It's called bioluminescence. It's essentially a special chemical reaction that takes place in their body, where a molecule called luciferin combines with oxygen to create light."
    emi "That's so interesting! I didn't think you could produce light through a chemical reaction."
    akira "It's actually more common than you think."
    akira "Fire gives off light, right? When you burn wood or light a match, that's a chemical reaction in itself."
    akira "But fire would harm the firefly, so using a chemical reaction is a good way for them to create light without getting too hot."
    emi "That makes sense, but why do they need light in the first place?"
    akira "To attract mates. The males will usually fly around, flashing their lights to make a signal that's unique to their kind."
    akira "If there's an interested female, she'll signal back, so that the male comes to her."
    emi "Wow, so we're in the middle of one big mating session then?"
    narrator "Akira bursts out laughing, sending a wave of serotonin through my body. A smile tugs at the corners of my lips, a sense of pride washing over me for my sarcastic humour."
    emi "What? Isn't that what you basically said?"
    akira "Technically, you're not wrong. It's just funny hearing you say that so bluntly."
    emi "Well, I'd like to be aware of when I'm being a third wheel to thousands of fireflies flying around."
    akira "If you think of it that way, then so be it."
    narrator "The both of us smirk at each other, amused by the thought."
    akira "By the way, are you scared of bugs?"
    narrator "I shake my head, curious about where this is going."
    emi "No, I'm fine with them. Why do you ask?"
    hide akira with dissolve
    narrator "Just then, he swings his arms out of nowhere and approaches me with cupped hands."
    show akira with dissolve
    akira "Here, hold out your hands and take a look at this. Try not to flinch."
    narrator "Akira gently places his hands in mine, and I gasp softly."
    narrator "In my hands rests a little firefly that he caught just moments ago. Although its body is nearly the size of a grain of rice, its light shines strongly, illuminating our faces like a beacon."
    emi "What a wonderful glow. . ."
    akira "I thought you might like it. You should've seen the way your eyes lit up when I placed it in your hands."
    narrator "I look up at Akira, who's watching me with a faint smile as the firefly's glow warms his face."
    narrator "I can't help but smile back, as the little creature takes off and joins its friends in their entrancing dance."
    scene blank with bgwipe
    scene forest_path with bgwipe
    show akira with dissolve
    narrator "After a while, we reluctantly decide to retire for the night."
    narrator "The soft glow of the moon casts long shadows across the ground, lighting the way back to Yuugen House."
    narrator "In the span of a few minutes, the house's silhouette appears in the distance. It's as quiet as the forest, now that it is well into the night."
    narrator "As we approach the end of our adventure, I feel a sense of contentment, glad that I was able to go on such a wondrous journey."
    scene blank with bgwipe
    scene yuugen_common with bgwipe
    show akira with dissolve
    narrator "Just as I'm about to head up to my room, I turn to Akira."
    emi "Thanks for letting me tag along, Akira. I enjoyed myself."
    akira "I'm glad to hear that. Your company was well appreciated."
    akira "I'll be sure to invite you to go stargazing next time. It really can't compare to tonight's view."
    emi "I'll be looking forward to it. Have a good night!"
    akira "You too."
    hide akira with dissolve
    narrator "With a final smile, the both of us head to our rooms to retire for the night."
    return
