# chore flags
default swept_foyer = False
default dusted_books = False
default collected_dishes = False
default chores_left = 3
default TOTAL_CHORES = 3

label cafe_intro:
    scene cafe with fade
    emi "Thank you for coming!"
    narrator "A bell chimes at the front of the store, signaling the end of the chaotic lunch hour."
    emi "(Phew, that's the last customer! I can finally catch my breath. . .)"
    narrator "Today had been unusually hectic. It was peaceful at first, with only a handful of regulars popping in for their morning coffee or bagel."
    narrator "As the day progressed, more and more customers trickled in, looking for a refreshment to enjoy."
    narrator "Before I knew it, the store had filled up in the blink of an eye."
    narrator "For hours, I scrambled in every direction, alternating between the floor and counter, as I relayed orders to Ingram."
    emi "(Somehow, I made it through. . .Thank God it's over.)"
    narrator "I collapse into a chair at a nearby table, stretching my arms in an attempt to relieve the tension in my muscles."
    narrator "Out of nowhere, a light poke taps at my shoulder."
    narrator "I turn to see Ingram standing there, with two icy drinks in hand."
    show ingram with dissolve
    ingram "Good job, you managed pretty well out there."
    ingram "Here, I made some iced coffee."
    ingram "I figured you might need a little treat to cool off and recharge. Go on, drink up."
    narrator "He takes the seat in front of me, passing one of the drinks my way."
    narrator "With the glass in hand, I take a small sip, trying not to mess up my uniform."
    emi "(Oh? This coffee. . .)"
    narrator "My tastebuds are greeted by a delightful sweetness, a subtle hint of vanilla hidden within."
    narrator "In an instant, my sweet tooth kicks in, tempting me to devour the whole thing."
    narrator "Small mouthfuls quickly turn into bigger gulps."
    narrator "Next thing I know, there's only a few ice cubes remaining at the bottom of my glass."
    emi "(That really hit the spot! I feel all refreshed now.)"
    narrator "I glance at Ingram, who's casually leaning against the back of his chair in a nonchalant manner. With a leg over the other, he continues to enjoy his drink."
    narrator "His face is brimming with vitality, not a sign of exhaustion to be seen."
    emi "(. . .If I didn't know any better, it'd be hard to believe there was even a crowd earlier.)"
    emi "(Does this happen regularly? How does he do it?)"
    emi ". . .You know Ingram, you're really impressive."
    emi "Earlier, you were pumping out drinks like no tomorrow. But right now, you look like you're in vacation mode."
    emi "Meanwhile there's me, who could barely able to keep up with all the orders. I never even knew things could get that busy!"
    ingram "Hmm, well, you are pretty new to this."
    ingram "Some days are on the slower end, but there are days like today where things can get crazy."
    narrator "He straightens his back, setting down his now empty glass."
    ingram "It's all about finding the right rhythm and keeping things organized."
    ingram "It's natural to feel overwhelmed at first, but I trust you'll pick things up soon. "
    ingram "Eventually, you'll be able to breeze right through the rush hours as well."
    narrator "I gulp nervously at Ingram's words. He's probably trying to encourage me, but the pressure to do well feels kind of. . . intimidating."
    narrator "The idea of handling so many orders at once still seems like a faraway dream. I can't imagine being on the same level as him."
    emi "(Maybe in a million years, I'll get there. . . surely. . .)"
    narrator "Ingram gets up from the table, collecting the two glasses as he heads back to the counter."
    narrator "I quickly follow suit, feeling somewhat rejuvenated from the short coffee break."
    ingram "Well, now that we've caught our breath, it's time to tackle the next tasks on our list."
    narrator "His words catch me off guard, and I nearly choke."
    emi "Wait, what? There's more?"
    ingram "Hmm? Of course, we're only halfway through the day. There's still lots to do."
    narrator "My heart sinks. The happy, nonchalant mood from earlier disappears, replaced by a looming sense of dread as I'm reminded that the day isn't quite over yet."
    narrator "I watch as Ingram fills the coffee grinders, my limbs growing heavier by the second."
    emi "(There's no way around this, is there?)"
    emi ". . .*sigh*."
    emi "Alright then. What do we have to do?"
    narrator "He looks over at me, his smug smile unwavering. He seems almost gleeful, as if he's looking forward to putting me to work."
    ingram "Well, for starters, there's a little housekeeping that needs to be done."
    ingram "Let's see. . ."
    ingram "Well, the foyer needs some sweeping. . . and there's empty dishes that need to be collected. Oh, and the library could use some dusting."
    emi ". . ."
    emi "We still have to do all of that. . .?"
    ingram "Mmhm. There's always something to do, but don't feel too pressured."
    ingram "You have all day to get through everything."
    ingram "Just take it one task at a time, and it'll be over before you know it."
    emi "Urgh. . . I guess it has to be done one way or another."
    emi "What about you then? What are you gonna be doing?"
    ingram "Well, someone has to be there to handle the customers, right? I'll be doing my barista duties and manning the cash register."
    ingram "You're still learning the ropes, so I think it's best if I handle those tasks for now."
    ingram "At least, until you're more comfortable with everything."
    emi "Oh. . . I guess that makes sense."
    ingram "Alright, let's get down to business then."
    ingram "I'm going to refill some of the pastries in the display case. You can find anything you need in the back."
    emi "Ah, yes boss!"
    hide ingram with dissolve
    narrator "As he heads over to the other side of the counter, I turn around, facing the direction of the storage room."
    emi "(Okay, let's do this!)"
    emi "(Just like he said, this will all be over before I know it!)"
    narrator "I smack my face twice in an attempt to pump myself up."
    ingram ". . .pfft."
    show ingram with dissolve
    narrator "Hearing a snicker from behind, I spin around, finding myself face to face with Ingram once more."
    narrator "His lips twitch at the corners, his entire body quivering in an attempt to stifle a laugh."
    ingram "Sorry, I didn't mean to interrupt your. . . *moment*."
    emi "(Oh no, it's over. . .He definitely saw everything just now. . .)"
    ingram "Should I be worried for your sanity? Maybe you should take the rest of the day off."
    narrator "A blush creeps across my cheeks as Ingram's gaze lingers on me."
    emi "I'm perfectly fine, thank you! I was just trying to, um, motivate myself."
    emi "Besides, I thought you went to go fill up the display case!"
    ingram "I was *going* to, but I forgot to tell you something."
    ingram "I didn't expect you to resort to such extreme measures as soon as I turned my back though. . ."
    ingram "Maybe I should've made you two coffees earlier. That way, you wouldn't have to abuse yourself to stay motivated."
    narrator "He nearly loses his composure, but manages to keep himself together at the last second."
    narrator "The burning sensation in my face festers, spreading up to the tips of my ears."
    emi "(. . .isn't he enjoying this a little too much?)"
    emi "(I better change the subject before he says anything else. . .)"
    emi "A-anyway! What was it that you wanted to tell me?"
    ingram "Right, I wanted to let you know that you might meet some of the others who also live at Yuugen House."
    ingram "They often lounge around the cafe at this time."
    ingram "It might be a good chance for you to introduce yourself and get to know them a bit if you'd like."
    emi "That's fair. What are their names?"
    ingram "There's Kai, Annelise and Akira. I've mentioned your name before, so they should be aware of who you are."
    ingram "If you haven't met any of them already, today might be your chance. I'm sure they'll be happy to meet you."
    emi "Kai, Annelise and Akira. . . alright, I'll remember that."
    emi "Well then, I'll get right on those chores now. Be back soon!"
    ingram "Sounds good. I'll be right here if you need anything."
    ingram "Just try not to resort to such. . . painful methods next time."
    emi "Ahhh!! Stop bringing it up!"
    narrator "Ingram smirks as I try and shoo him away."
    hide ingram with dissolve
    narrator "Once he's out of sight, I start making my way over to the back storage room."
    scene blank with bgwipe
    scene storage_room with bgwipe
    emi "Whoa, this place is surprisingly clean!"
    narrator "Rows of shelves line the walls from floor to ceiling, holding various cleaning supplies."
    narrator "From disinfectant bottles to neatly folded cloths, they are all meticulously arranged by type, making them easy to find and grab."
    narrator "On the opposite end of the room is a large cooler. It seems to be well-maintained, containing unopened cartons of milk, cream and other baking ingredients."
    narrator "Running a finger along one of the shelves, I find that there's not a speck of dust to be found. The place was absolutely spotless."
    emi "(Everything's so neatly organized.)"
    emi "(Did Ingram do all of this too? He really is on a different level. . .)"
    narrator "I look around, searching for the tools I need to finish my chores."
    emi "(Okay, so there's a broom in the corner, a feather duster on the wall, and cleaning rags on one of the shelves.)"
    emi "(Hmm. . . what should I start with?)"
    return
