label dreaming_of_school:
    scene blank with bgwipe
    scene bedroom_night with bgwipe
    emi "(Finally, my sweet bed!)"
    narrator "I collapse onto the plush covers of my bed, feeling fatigue creeps into my limbs."
    narrator "Having been untouched the entire day, the bed is at the perfect temperature, enveloping me in a cool, soothing embrace."
    narrator "As I slip under the blanket, I gaze at the soft moonlight filtering through the window, casting a gentle glow that almost lulls me to sleep."
    emi "(It's strange to think that this room used to feel so foreign, but now, it's becoming pretty comfy.)"
    emi "(I wonder why this place feels so welcoming. Is it because of the peaceful atmosphere? Or is it because of the people staying here. . .?)"
    narrator "A tender, happy feeling spreads through my chest as I picture everyone's faces."
    emi "(I could get used to this.)"
    emi "(But I can't stay here forever. . . Someday, I'll recover all my memories and I'll have to leave.)"
    narrator "I ponder over the customers I've helped so far, recalling all the memories I've encountered during spirit guiding."
    narrator "The uncertainty of whether I'm currently alive or not weighs on me, and an anxious feeling residing at the back of my mind resurfaces."
    emi "(Why am I here? What was my life like?)"
    emi "(Was I in an accident, or did I do this to myself. . .?)"
    narrator "Difficult questions swirl around in my mind, but they remain unresolved, leaving me feeling more anxious by the second."
    narrator "I shake my head, cutting off my train of thought."
    emi "(I'm going to be up all night if I keep thinking about this.)"
    emi "(It's been a long day. I should get some rest.)"
    scene blank with fade
    narrator "I close my eyes and turn to the side, clutching the blanket as I find a comfortable position."
    narrator "Taking deep breaths, my body warmth mingles with the bed covers, wrapping my body in a cocoon of comfort that eventually pulls me into a deep slumber."
    narrator ". . ."
    scene blank with bgwipe
    uk_generic "Okay, gather around everyone!"
    uk_generic "Hey, you there! Can you move over a bit? I can't see that guy behind you."
    uk_generic "Alright, hold that pose! Say cheese in 3. . ."
    uk_generic "2. . ."
    uk_generic "1. . ."
    uk_generic "Cheese!"
    scene blank with Fade(0.08, 0.0, 0.15, color="#fff")
    scene school_entrance with fade
    narrator "A group of excited students gather around, sporting what seems to be volleyball uniforms."
    narrator "Behind them is a staircase leading to the main entrance of a school building, framed by several pink petals fluttering from the cherry blossom trees around."
    past_emi "Okay, looks good! Thanks everyone, this is going to go right in the yearbook!"
    narrator "I glance down at the camera in my hands, taking in the group photo displayed on the screen. Unlike the sports team in front of me, I'm wearing a school uniform."
    emi "(This scene feels familiar. . . Is this another memory of mine?)"
    manager "Thanks for coming out to take our photo, Emi!"
    manager "I'm sure it isn't easy to find time in your schedule when you're so busy with the school committee stuff."
    past_emi "Oh, it's alright! I'm always happy to lend a hand."
    past_emi "Staying busy just means I can help more people."
    manager "You're so trustworthy. We can always count on you!"
    emi "(That's right, I remember. . .I was so involved in middle school. I barely had time for myself.)"
    emi "(But despite all that, I was happy whenever someone complimented me. It was worth seeing their smiles.)"
    emi "(After all, I wanted to be loved. . .)"
    scene blank with w12
    scene classroom_sunset with wet
    narrator "The scene shifts. I'm now in an empty classroom, holding a stapler in one hand and a stack of paper handouts in the other."
    narrator "The sunset pierces through the window, casting a golden, nostalgic atmosphere across the room."
    narrator "I staple the handouts, the repetitive crunching of paper under the stapler feeling almost hypnotic."
    narrator "The pile in front of me slowly decreases as I work, and I find a comfortable rhythm."
    narrator "Suddenly,. I hear faint laughter coming from outside, and I glance down from the window. There's a group of friends leaving the school gates, immersed in cheerful conversation."
    narrator "A pang of loneliness hits me, my clutch on the stapler tightening slightly."
    emi "(This feeling. . .)"
    emi "(I volunteered to become the class rep one day, in an attempt to put myself out there and get to know my classmates.)"
    emi "(Gradually, they started taking notice of me and I got to know everyone's names.)"
    emi "(But sometimes. . . it felt so lonely.)"
    narrator "As I'm lost in thought, the classroom door swings open. A figure steps in, but their face is hazy. Even after squinting, I'm unable to make out any of the details on them."
    narrator "They approach me with an air of confidence and warmth, and I'm struck with an odd sense of familiarity upon seeing them."
    uk_generic "Emi, you're still here? You've been working so hard!"
    uk_generic "You need to take a break once in a while, you know. Everyone appreciates what you do, but you shouldn't push yourself so much."
    narrator "A sense of reassurance washes over me. This person feels like a close friend."
    past_emi "Yeah, I know. . . It's just that Mr. Tachibana is counting on me to get this done and I want to make sure everything's perfect."
    uk_generic "And it always is, because you put so much care into it!"
    uk_generic "But remember, people might take advantage of you if you don't take care of yourself."
    past_emi ". . .You're right."
    uk_generic "Aw, don't look so sad. I'm just worried about you, especially when you can't say no to anybody."
    uk_generic "Here, let me help bring those to the staff lounge!"
    past_emi "What? No, it's okay, you don't have to-!"
    uk_generic "Oh relax, I've been waiting for you this whole time so that we can go home together. At least this gives me something to do."
    past_emi ". . .Thank you."
    scene blank with fade
    narrator ". . ."
    return
