label meeting_others:
    emi "Actually, speaking of which, I ended up meeting the other roommates while going around the cafe."
    ingram "Ah, so you did end up seeing them after all. How did your introductions go?"
    emi "Well, earlier, I helped Kai find a charm that fell off his bracelet. And I also gave him one of the desserts that were taken off-display."
    ingram "Let me guess, he was so focused on searching for his charm that he ended up skipping lunch."
    emi "That's right! How did you know?"
    ingram "That's just Kai being Kai. He wears his heart on his sleeve, so it's easy to tell how he'll act in certain situations."
    ingram "Based on your experience with him, I'm guessing you can relate."
    emi "Absolutely. He was so energetic, like a human lightning bolt!"
    ingram "Yeah, I don't know where he gets it from. I wish he channeled that energy into something other than his crazy ideas, but he's a good guy at heart."
    ingram "You can't stay mad at him for long."
    emi "That's true. . ."
    emi "I also chatted with Akira briefly. I forgot to mention it to you earlier, but I actually ran into him at Yuugen House before. It was after our spirit guiding session from last time."
    emi "We didn't talk very much, but somehow he recognized me."
    ingram "Ah, Akira. I can always count on him, especially when it comes to keeping Kai in line. He's quite capable, so there's no need to worry too much about him."
    ingram "He's been around the longest out of everyone, so he knows this place like the back of his hand."
    ingram "If you need advice or a different perspective, he's a good person to ask."
    ingram "That includes insight into recovering your memories."
    emi "That's fair. When I was talking with him, he seemed super insightful, as if there's a lot going on inside his head."
    ingram "He's definitely nowhere as expressive as Kai, but you can be sure that there's always brewing something inside that head of his."
    ingram "He also doesn't beat around the bush, so he's refreshing to talk to."
    emi "I agree, I also feel the same way."
    emi "Ah, and when I went to the library, I came across Annelise while she was in the middle of reading."
    emi "She's a lot more soft-spoken than Kai, but she's super sweet."
    emi "It took some time for her to warm up to me, but once we got on the topic of books, she suddenly got a lot more talkative!"
    ingram "That's Annelise for you. When she first came to Nobaros, she holed herself up in her room and didn't want to talk to anybody."
    ingram "But I managed to get her to open up a little bit when I gave her some novel recommendations a while back. Since then, I've never seen her without a book in her hands."
    ingram "If you get a chance to interact with her more, I'm sure she'd appreciate having more book buddies to talk to."
    emi "Oh for sure! She recommended her favourite book to me, so I plan on reading it later."
    narrator "Ingram's eyes crinkle, and a delightful hum resonates in his voice. He seems pleased to hear about my interactions with the others."
    ingram "It seems like you had a good time meeting everyone."
    emi "Yes, they're super nice and friendly!"
    emi "I just wish I had more time to get to know them."
    ingram "Don't worry, there's no rush. They'll be at Yuugen House once we wrap things up here."
    ingram "You'll get to talk to them all you'd like then."
    narrator "I let out an exasperated sigh, feeling a bit impatient."
    narrator "It feels good to see how much I've accomplished since the start of the day, but I can't wait to head home and get to know everybody better."
    emi "(Shouldn't time pass by faster if I'm busy?)"
    emi "(I guess it is what it is. . .)"
    return
