label continue_dusting:
    narrator "I decide to leave Annelise alone, figuring that she probably just found more books to read."
    scene library with fade
    show emi with dissolve
    narrator "Eventually, I manage to finish dusting all the shelves in no time."
    emi "(Hmm, somehow that felt a lot quicker than I expected. . .)"
    show emi at right with move
    show annelise at left with dissolve
    narrator "I glance over at Annelise, who hasn't moved an inch since we conversed earlier."
    narrator "She has yet to notice that I finished dusting the shelves."
    emi "(That book pile is really growing by the minute. . .)"
    narrator "I decide to approach Annelise, curious about the books sitting beside her."
    emi "Annelise, are you a big reader? I couldn't help but notice that you have quite a few books in your pile."
    emi "That's a lot to read in one day, isn't it?"
    narrator "Annelise snaps back to reality as she looks up from her book, surprised by my question. It seems she wasn't expecting me to make conversation with her."
    annelise "Eh? {w=0.2}Ah yes, I really enjoy reading. I usually get so immersed in the story that I often tune out of reality."
    annelise "When that happens, time just flies right by."
    emi "That sounds fun! It's almost as if you're time travelling."
    annelise ". . .!"
    annelise "Yes, {w=0.2}that's exactly how it feels!"
    annelise "Imagining what could happen if I did certain things differently than the main character feels wondrous."
    narrator "Annelise perks up, suddenly more engaged in the conversation. She must be excited to talk about what she's reading."
    emi "So what are you currently reading? You seem so focused on it."
    emi "Is it a good story?"
    annelise "Oh, this is my favourite book! Let me show you."
    narrator "Annelise's face brightens at the mention of the book she's reading. Her eyes shine with joy, and a radiant smile spreads across her face."
    narrator "Filled with cheerful spirit, she rises to her feet and skips over in a capricious, graceful manner, like she's floating on air."
    narrator "She presents the book to me, holding it out like a precious treasure. There's an air of pride and joy about her, reminiscent of an adorable child showing off their favourite toy."
    narrator "It's like the timid girl I encountered earlier has disappeared completely."
    annelise "Here, it's called Hiraeth. It may not look very interesting at first glance, but I highly recommend it!"
    annelise "It's about a young artist named Elara. She experiences these extraordinary dreams where she visits a mystical land called Hiraeth, filled with enchanting mysteries and sights as far as the eye can see."
    emi "That sounds fascinating! What do you like about it?"
    annelise "I really admire Elara's strength!"
    annelise "Despite being a struggling artist with lots of challenges to overcome, she manages to find inspiration in her journeys to Hiraeth."
    annelise "Each new discovery she comes across fuels her creativity, leading to her next big artistic breakthrough!"
    annelise "I aspire to be as courageous as her one day. Her adventures sound so exhilarating!"
    narrator "I can't help but smile at Annelise's enthusiasm as she gushes about the novel."
    narrator "She notices my smile, and realizes she's been chatting non-stop for a while. She suddenly stops, cutting herself off."
    annelise "Ah, sorry! I'm probably boring you with all of this. . ."
    emi "No, not at all! I enjoyed listening to you talk! If anything, it makes me want to read the book too."
    narrator "Just then, a small piece of paper slips out from the book, floating gently to the ground between us."
    narrator "As I bend down to pick it up, Annelise quickly snatches it before I can. I look up at her, noticing a faint blush on her cheeks."
    emi "Oh, is everything okay?"
    annelise "Huh? Oh, yes, it's nothing. . ."
    annelise "I just. . . I sometimes like to sketch too. It's embarrassing, so I'd prefer if you don't tell anybody else about it."
    emi "Oh, I understand! Your secret is safe with me."
    narrator "Annelise visibly relaxes, breathing a sigh of relief. It seems she's a bit shy about sharing her art with others."
    emi "Alright! I'll have to get back to doing chores soon, or else Ingram will come looking for me."
    emi "Would you like anything to drink? You've been talking for a while, so maybe a refresher might help?"
    narrator "Annelise shakes her head, holding Hiraeth close to her chest."
    annelise "No thank you, I think I'm okay! Thank you for asking though."
    emi "Alright, sounds good. If you need anything, just let me know!"
    emi "I really have to go now, but it was nice meeting you."
    emi "Let's talk more about books when we're back at Yuugen House!"
    annelise "Yes, of course! I'd be more than happy to."
    narrator "Annelise bows slightly, a smile lighting up her face."
    narrator "I return the smile and wave as I exit the library, leaving her to her reading."
    hide emi with dissolve
    scene storage_room with fade
    show emi with dissolve
    emi "(That was pleasant! I didn't expect Annelise to be such a passionate book lover. Now I'm really curious about Hiraeth.)"
    emi "(I'll have to ask her for more recommendations later.)"
    return
