label lull_of_lavender:
    emi "(Let's drink some tea. I can always add some sugar in myself later.)"
    narrator "I grab the pitcher from the fridge, noticing a few tea leaves floating around in it."
    emi "(Hmm, let's find something to strain these out. Wouldn't want to have a bunch of leaves in my mouth.)"
    narrator "I rummage through the drawers, looking for a small strainer to place over a cup. Just as I manage to find one, I hear footsteps coming down the stairs."
    show annelise with dissolve
    narrator "Annelise walks into the kitchen, her eyes lighting up as she spots me with the pitcher."
    annelise "Oh, Emi! You found my black tea. Were you going to drink some just now?"
    emi "Eh? This is yours? Sorry, I didn't know!"
    emi "I can put it back if you'd like. I was just looking for something to cool me down after taking a bath earlier."
    narrator "Annelise giggles timidly, hiding her mouth behind a hand."
    annelise "No, it's okay. Let's enjoy this tea together. I can make a special drink for you."
    narrator "She heads to the pantry, pulling out a small glass jar filled with what seems to be some kind of syrup."
    narrator "She unwraps the cloth tied around the lid, revealing a glossy, fragrant substance that smells slightly floral."
    annelise "This is homemade lavender syrup. I usually like to mix it with the tea to make what's called a London Fog."
    annelise "Although in this case, the lavender syrup adds a special twist to the drink."
    emi "London Fog? I don't think I've heard of that before, what kind of drink is it?"
    annelise "It's sort of like a tea latte! If you add some frothed milk and vanilla, it has this subtly sweet and creamy taste to it."
    emi "Oh, that sounds wonderful! I'd love to have a cup."
    narrator "Annelise smiles shyly, and happily nods in acknowledgement."
    annelise "Yes, I think you'd like it."
    narrator "With a skip in her step, she brings out two decorative mugs and fills them with black tea."
    narrator "I watch as she proceeds to grab the milk out of the fridge, a look of surprise on her face as she observes the bottle in her hand."
    annelise "Oh, we're almost out of milk. . ."
    emi "Oh right, I was considering drinking it earlier, but I didn't want to finish the bottle in case someone else wanted some. Do you think there's enough?"
    annelise "Mmm, I think this might just be the right amount. I'll have to tell Ingram that we need more. . ."
    emi "That's perfect! Don't worry, I can pass on the message when I see him tomorrow. Let's just finish the rest of the bottle then."
    annelise "Okay, let's go with that."
    narrator "Annelise smiles excitedly, and I'm overwhelmed by the irresistible urge to squish her cheeks."
    emi "(No! I can't, I don't want to scare her away. She might still be a little shy around me, since we just met earlier. . .)"
    annelise ". . .Emi, you wanted something cold to drink, right? I usually make my London Fogs hot, but I can make a cold version if you'd like."
    emi "Really? I'd appreciate that, thank you!"
    emi "How do you make it cold though, don't you need to heat the milk and froth it?"
    narrator "She shakes her head, bringing out a weird-looking glass container. There's a spout on its rim that resembles a teapot, but the mesh filter on the inside throws me off."
    annelise "This is called a French press! Ingram showed me how to use it a while back."
    annelise "Usually, it's used to brew coffee since the mesh can be used to filter out the coffee grounds, but I've learned that you can also use it to froth cold milk!"
    emi "That seems pretty useful! That way, you don't have to go through the effort of heating up the milk."
    annelise "Yup, that's right. It's pretty convenient."
    narrator "Annelise pours a bit of milk into the French press, and begins vigorously pumping the rod attached to the mesh filter."
    narrator "I watch in fascination, seeing the milk begin to froth and expand in volume by the minute."
    emi "(Wow, she's really going at it. . .)"
    narrator "After a few moments of frothing, Annelise's movements grow sluggish and she slows down, clearly getting tired."
    emi "Here, let me have a go! You should rest your arms, that seemed like a lot of work."
    annelise "Huh? Oh, thank you. . ."
    narrator "She steps aside, catching her breath. I continue pumping the rod, amazed at how quickly the milk turns into a thick, velvety froth."
    narrator "After a minute or two, it's ready. I pour the frothy milk into the mugs while Annelise tops them off with a few drops of vanilla extract and lavender syrup."
    annelise "And we're finished! Here's your drink. Go ahead and have a sip."
    narrator "She passes me one of the mugs, which I graciously accept with both hands. As I bring the cup to my lips, a whiff of the lavender and vanilla tickles my nose."
    narrator "As soon as the drink hits my tongue, I'm greeted by a satisfying creamy flavour as delicate floral notes of lavender caress my taste buds."
    narrator "A subtle hint of vanilla follows after, providing a sweet undertone that pulls all the flavours together."
    emi "Wow, I don't think I've tasted anything like this before!"
    emi "The lavender and vanilla adds depth, but at the same time, it's not so overwhelming that it takes away from the milk tea base."
    narrator "Annelise blushes slightly, flustered to hear my praise."
    annelise "I'm glad you like it. To be honest, I was a bit nervous about whether I made it well or not."
    annelise "I do make this often, but it's the first time I'm having someone else try it. . ."
    annelise "The others don't drink tea that often, so I'm glad to see another tea lover."
    emi "Well, I think you did an amazing job. I didn't think you could do very much with tea other than add sugar or milk."
    narrator "She smiles tenderly at me, her face a mix of both relief and genuine happiness."
    narrator "I take another refreshing sip of the drink, relishing the effort and care that she put into making it for me."
    emi "You know, you kind of remind me of Ingram right now."
    annelise "Eh? How come?"
    emi "Well, you know how he's a barista right? Seeing you make this London Fog for me gave off the same vibes."
    annelise "Oh, I see. . .I didn't expect to hear that. He's always working so hard at the cafe, but I just like to experiment here and there. It's just a hobby honestly. . ."
    emi "Oh? What else have you made?"
    annelise "Erm. . .where do I start?"
    annelise "I guess you could say that any of the tea blends in the pantry is made by me."
    emi "Wow, actually? That's incredible, you must be quite skilled at it!"
    annelise "W-well. . .I'm not too sure about that. None of the others have tried them before. I enjoy them myself, but I might be biased."
    emi "Oh, how come? I feel like they'd enjoy something like this too."
    annelise " I don't know. . .I guess I'm just scared of seeing their reactions. I don't think I could handle it if they didn't like it."
    emi "No way! If they don't like it, then I'll sucker punch them right on the spot!"
    annelise "E-eh?!"
    narrator "Annelise bursts out laughing as I pretend to flex my arms, her usually timid voice resonating clearly in the air. Her happy laughter is contagious, and I find myself smiling alongside her."
    emi "In all honesty, you should have more confidence in yourself, Annelise. If it helps, I can be your taste tester. I'd love to taste whatever else you come up with!"
    annelise "R-really? Are you sure. . .?"
    emi "Of course! Here, I'll promise you."
    narrator "I extend a hand out to Annelise, sticking my pinky out towards her. She widens her eyes, not expecting me to initiate a pinky promise."
    narrator "After a moment, her expression softens and she links her pinky with mine, a heartwarming sense of camaraderie forming between us."
    emi "(Her fingers are so warm.)"
    annelise "Thanks for trying my tea, Emi. I hope that we can have tea together again sometime."
    narrator "Annelise's eyes glisten with emotion, her smile radiating with joy."
    emi "I'd love that! Just call me whenever, I'd accept your invitation anytime."
    narrator "As the night goes on, a friendly, cozy atmosphere fills the kitchen and we continue to sip our drink, enjoying each other's company."
    return
