label shelve_books:
    emi talk "Hey Annelise, do you need some help putting those books away? You can toss them my way if you want!"
    narrator base "Annelise looks up from her novel, her eyes sparkling as if I just read her mind. She eagerly nods in agreement."
    annelise "Yes, actually! I'm glad you asked, I got these books as a recommendation from Ingram, but I'm not tall enough to reach the shelf they came from."
    annelise "I didn't want to bother him because he looked so busy. There have been customers all day, so I haven't found a good time to ask him about it. . ."
    emi talk "That shouldn't be a problem! I'm here to tidy up the area anyways. Where do these books go?"
    narrator base "Annelise looks away with a bit of a guilty look. She points to a spot near the very top of one of the bookshelves in the wall."
    emi "(Oh. . . that spot might be just out of my reach.)"
    narrator "I pause for a moment, pondering how to reach the shelf Annelise pointed to."
    emi "(I could ask Ingram, but then nobody would be around to deal with customers. And the chairs around here might not be tall enough.)"
    emi "(I wonder if there's a ladder around that we could use. . .)"
    emi "(Oh! There might be one in the back room. There are all sorts of things back there, so surely that includes a ladder.)"
    emi talk "Just wait here Annelise! I'm going to check the back. There might be a ladder there that we can use."
    annelise base "That's a good idea! I'll be waiting then."
    scene blank with bgwipe
    scene storage_room with bgwipe 
    narrator base "I quickly rush out of the library and check the back room, shuffling through the cleaning supplies in search of anything that looks remotely like a step ladder."
    emi "(Hmm. . . I could've sworn there was one around here.)"
    emi "(. . . Ah! {w=0.2}There it is!)"
    narrator "My eyes spot a folded step ladder hidden behind one of the shelves. I make my way over and quickly grab it, brushing off any dust stuck to it."
    narrator "With the ladder in hand, I head back to the library where Annelise is waiting."
    scene blank with bgwipe
    scene library with bgwipe
    show annelise with dissolve
    emi talk "I'm back! And look what I found!"
    narrator base "As I show the ladder to Annelise, she looks at me in amazement and claps happily."
    annelise "Oh, there really was a ladder!"
    annelise "You're amazing Emi! Now we can put the books away, and I don't have to keep hoarding them by my side."
    narrator "Annelise smiles gently as she rises to her feet, carrying the stack of books over to me."
    narrator "I set up the ladder and carefully take a step, making sure that I have solid footing before climbing up to the top."
    narrator "Once I have a good view of the top shelf, I gesture for Annelise to pass me the books. She obliges, and we work through the stack slowly and methodically."
    scene blank with bgwipe
    scene library with bgwipe
    show annelise with dissolve
    emi talk "And that's the last one! Good work, thanks for helping me out!"
    annelise base "Oh no, it's my pleasure! If anything, I'm indebted to you."
    annelise "I didn't have the heart to burden you while you were dusting the shelves, so I really appreciate that you were willing to help. . ."
    narrator "Annelise twiddles with her fingers, a little flustered by my compliment."
    emi "(Is she not used to compliments? She's pretty shy huh. . .)"
    emi talk "Are you a big reader? I couldn't help but notice that we put away quite a few books."
    emi "Did you read them all today?"
    annelise base "Eh? {w=0.2}Ah yes, I really enjoy reading. I usually get so immersed in the story that I often tune out of reality."
    emi talk "That sounds fun! It's almost as if you're travelling to an entirely different dimension."
    annelise base "Yes, {w=0.2}that's exactly how it feels!"
    annelise "Imagining what could happen if I did certain things differently than the main character feels wondrous."
    emi talk "Do you have a favourite book?"
    annelise base "I do! Let me go grab it and show you!"
    narrator "Annelise's face brightens at the mention of discussing her favourite book. Her eyes shine with joy, and a radiant smile spreads across her face."
    hide annelise with dissolve
    narrator "Filled with cheerful spirit, she skips over to a nearby bookshelf in a capricious, graceful manner, like she's floating on air."
    narrator "She picks out a small novel, handling it with a gentle touch as she returns."
    show annelise with dissolve
    narrator "She presents the book to me, holding it out like a precious treasure. There's an air of pride and joy about her, reminiscent of an adorable child showing off their favourite toy."
    narrator "It's like the timid girl I encountered earlier has disappeared completely."
    annelise "This is it! It's called Hiraeth, and I highly recommend it."
    annelise "It's about a young artist. She experiences these extraordinary dreams where she visits a mystical land called Hiraeth, filled with enchanting mysteries and sights as far as the eye can see."
    emi talk "That sounds fascinating! What do you like about it?"
    annelise base "I really admire her strength!"
    annelise "Despite being a struggling artist with lots of challenges to overcome, she manages to find inspiration in her journeys to Hiraeth."
    annelise "Each new discovery she comes across fuels her creativity, leading to her next big artistic breakthrough!"
    annelise "I aspire to be as courageous as her one day. Her adventures sound so exhilarating!"
    narrator "I can't help but smile at Annelise's enthusiasm as she gushes about the novel."
    narrator "She notices my smile, and realizes she's been chatting non-stop for a while. She suddenly stops, cutting herself off."
    annelise "Ah, sorry! I'm probably boring you with all of this. . ."
    emi talk "No, not at all! I enjoyed listening to you talk! If anything, it makes me want to read the book too."
    narrator base "Just then, a small piece of paper slips out from the book, floating gently to the ground between us."
    narrator "As I bend down to pick it up, Annelise quickly snatches it before I can. I look up at her, noticing a faint blush on her cheeks."
    emi talk "Oh, is everything okay?"
    annelise base "Huh? Oh, yes, it's nothing. . ."
    annelise "I just. . . I sometimes like to sketch too. It's embarrassing, so I'd prefer if you don't tell anybody else about it."
    emi talk "Oh, I understand! Your secret is safe with me."
    narrator base "Annelise visibly relaxes, breathing a sigh of relief. It seems she's a bit shy about sharing her art with others."
    emi talk "Alright! I'll have to get back to doing chores soon, or else Ingram will come looking for me."
    emi "Would you like anything to drink? You've been talking for a while, so maybe a refresher might help?"
    narrator base "Annelise shakes her head, holding Hiraeth close to her chest."
    annelise "No thank you, I think I'm okay! Thank you for asking though."
    emi talk "Alright, sounds good. If you need anything, just let me know!"
    emi "I really have to go now, but it was nice meeting you."
    emi "Let's talk more about books when we're back at Yuugen House!"
    annelise base "Yes, of course! I'd be more than happy to."
    narrator "Annelise bows slightly, a smile lighting up her face."
    narrator "I return the smile and wave as I exit the library, leaving her to her reading."
    scene blank with bgwipe
    scene storage_room with bgwipe
    emi base "(That was pleasant! I didn't expect Annelise to be such a passionate book lover. Now I'm really curious about Hiraeth.)"
    emi "(I'll have to ask her for more recommendations later.)"
    return
