label family_memory_1:
    scene bedroom_night with bgwipe
    scene black with fade
    "You drift into sleep the moment your head touches the pillow."
    "The weight of the day melts away, replaced by something warm… familiar."
    scene spring_day with dissolve
    "A gentle breeze carries the scent of wildflowers."
    "{color=#8489ff} Show an image of a small child's hands clutching a paper cup filled with juice. You are looking down at this.{/color}"
    "{color=#8489ff}A laugh rings out nearby—bright, unmistakably fond.{/color}"
    uk_generic "[emi_name]! Come and help us unpack the picnic basket."
    past_emi "Okay, coming!"
    "{color=#8489ff}Show an image of a basket filled to the brim. There are sandwiches wrapped in wax paper. Cut fruit. Homemade pastries.{/color}"
    past_emi "Uwa~! There's so much food!"
    uk_generic "That's right, your mom worked extra hard to prepare it this morning."
    uk_generic "What should we say to her?"
    past_emi "Thank you mommy! I love you!!"
    "{color=#8489ff}Special CG of your mom. It's blurry so you can't quite make out their faces.{/color}"
    "{color=#8489ff}I also haven't decided on how to differentiate between the mom VS dad character names. {/color}"
    uk_generic "You’ve got jam all over you again, honey."
    uk_generic "Here, let me wipe it off for you."
    past_emi "No, let me lick it! I want the jam!"
    uk_generic "Oh, you always eat so well! I bet you're going to grow up big and strong one day."
    "{color=#8489ff}Special CG of your dad. It's also blurry.{/color}"
    uk_generic "Just like daddy, right?"
    past_emi "No! I want to be like mommy!"
    past_emi "She's pretty and nice and a superhero!"
    uk_generic "Is that so! Haha, whatever you want honey."
    "{color=#8489ff}Special CG of both parents.{/color}"
    "Laughter fills the air."
    "The sun filters through the trees, dappling the blanket in gold."
    "The quiet hum of insects and distant birds fill the air."
    if emi_name.capitalize() == "Emi":
        "{color=#8489ff}Special lore tidbit if the player went with the default name 'Emi'.{/color}"
        past_emi "Mommy, daddy, why is my name [emi_name]?"
        uk_generic "It's a special name, just for you. It means 'beautiful blessing' in Japanese."
        uk_generic "And that's exactly what you are to us, a beautiful blessing."
        uk_generic "It's also a name that carries both of your French and Japanese heritage."
        uk_generic "You know? Your father wanted to name you 'Emile' if you were a boy."
        past_emi "No!! I like Emi better!"
        uk_generic "H-hey! I thought it was a nice name. {color=#8489ff}(This is the dad.){/color}"
        past_emi "Just give me a little brother, then you can name him Emile!"
        uk_generic "Oh? Do you want a little brother, [emi_name]?"
        past_emi "Yeah! Or a little sister! I just want someone to play with!"
        uk_generic "Haha well, we'll see about that."
        uk_generic "For now, you can just enjoy being our little darling [emi_name]."
    scene blank with fade
    emi "(It feels… safe.)"
    emi "(Really safe.)"
    emi "(That's right...)"
    emi "(Every birthday, anniversary, sunny day...)"
    emi "(We always made sure to go on a family trip, whether it was far away or the nearby park.)"
    emi "(Mom's cooking was the best.)"
    emi "(Dad would always hold my hand to keep me from running off.)"
    emi "(Even if I don’t fully remember them yet… I can feel them.)"
    emi "(I was… happy.)"
    emi "(If that was just one day of my life…)"
    emi "(Then maybe… there are many more like it.)"
    "CHAPTER 1 COMPLETE"
    return