label family_memory:
    scene black
    with fade
    "You drift into sleep the moment your head touches the pillow."
    "The weight of the day melts away, replaced by something warm… familiar."
    scene spring_day with dissolve
    "You’re sitting on a blanket spread across sunlit grass."
    "A gentle breeze carries the scent of wildflowers."
    emi "(…Huh?)"
    "You look down."
    "Your hands are smaller than you remember."
    "They clutch a paper cup filled with juice."
    "A laugh rings out nearby—bright, unmistakably fond."
    "Someone calls your name."
    "You turn."
    "A picnic basket sits open, packed to the brim."
    "Sandwiches wrapped in wax paper. Cut fruit. Homemade pastries."
    "Two figures sit across from you."
    "You can’t see their faces clearly."
    "They’re blurred, like reflections in water."
    "But you feel it instantly."
    emi "(Mom… Dad…?)"
    "One of them reaches over and gently wipes something from your cheek."
    uk_generic "You’ve got jam all over you again."
    "You giggle."
    emi "(I… I’m laughing.)"

    "The sound feels strange."
    "Natural."
    "Effortless."
    "The sun filters through the trees, dappling the blanket in gold."
    "You lean back, listening to the quiet hum of insects and distant birds."
    emi "(It feels… safe.)"
    emi "(Really safe.)"
    "A warmth blooms in your chest."
    "Not excitement."
    "Not excitement like adventure."
    "Something steadier."
    "Love."
    emi "(I was… happy.)"
    "The realization settles gently, like a truth you’ve always known."
    emi "(I wasn’t lonely.)"
    emi "(I wasn’t struggling.)"
    "You close your eyes, basking in the moment."
    "You imagine birthdays."
    "Candlelight. Smiles. Laughter."
    "You imagine trips."
    "Hands held tight. Voices calling you back if you wander too far."
    "You imagine growing older."
    "Supported. Encouraged."
    emi "(There were so many good days.)"
    emi "(Even if I don’t remember them yet… I can feel them.)"
    "The warmth doesn’t fade."
    "It lingers, wrapping around your heart like a promise."
    emi "(I think… I was really lucky.)"
    emi "(If that was even one day of my life…)"
    emi "(Then maybe… there are many more like it.)"
    scene blank with dissolve
    "CHAPTER 1 COMPLETE"
    return