label new_customer_1:
    "Just then, there’s a soft knock at the front door."
    emi "Eh?"
    hide ingram with dissolve
    "You walk over to open the door."
    show brio with dissolve
    "A middle-aged man stands there, shoulders squared despite the fatigue in his eyes."
    hide brio with dissolve
    show ingram at left with dissolve
    "You glance at Ingram and keep your voice low."
    emi "Ingram, is he...?"
    ingram "Let him in. He's a customer."
    emi "G-gotcha!"
    emi "Welcome to Nobaros Cafe sir! Please, come right in."
    "You step aside and let the man in."
    show brio:
        offscreenright
        ease 1.5 xalign 0.8
    "{w=1.5}Without a word, the man takes a seat as Ingram introduces the both of you."
    "Ingram proceeds to bring out the special drink menu, offering him something warm to drink."
    ingram "Please, feel free to take your time."
    uk_generic "...I'll have a latte, please. No sugar."
    ingram "Understood. We'll have that ready in a bit."
    hide brio with dissolve
    show ingram:
        left
        ease 1.0 center
    "{w=1.0}Ingram looks at you and smiles."
    ingram "So, up for the task?"
    emi "...Eh? Y-you want me to make it?"
    emi "Are you sure about that? What if I mess it up?"
    ingram "It doesn't need to have beautiful latte art."
    ingram "You already have the basic steps down, you can do this."
    emi "..."
    emi "Okay, I'll do it."
    hide ingram with dissolve
    "You get to work, carefully working through every step Ingram taught you."
    "As you finish up with the milk steamer, you see Ingram adding some Lunaria essence to the cup."
    emi "(What a pretty shine... I wonder how Ingram gets those vials.)"
    show ingram with dissolve
    ingram "Hm? Is something wrong?"
    emi "Oh, I was just distracted by how pretty the Lunaria essence looks."
    emi "How do you get those vials anyways?"
    ingram "It's extracted from Lunaria flowers through a long process, but the details are a secret."
    ingram "Sorry for blocking the way, you can finish up now."
    hide ingram with dissolve
    emi "(Okay, just need to pour the milk now. Deep breaths [emi_name]...)"
    "{color=#8489ff}Cue maybe a small latte art mini game here. Potentially could be a 'minigame challenge' after a minigame portion in [emi_name]'s initial cafe training. {/color}"
    "When you hand the cup over, the man takes a sip."
    show brio at Position(xalign=0.8)
    show ingram at left
    with dissolve
    uk_generic "…That’s good."
    "A smile warms his face, and his expression lightens."
    ingram "How do you feel, mister...?"
    brio "You can call me [ch1_name]."
    brio "This is a lovely latte, thank you for making it."
    brio "It's been a while since I felt so light."
    brio "So, could you tell me more about this place? Where am I exactly?"
    "The man listens intently as Ingram tells him about Nobaros and the spirit guiding process, nodding occasionally."
    uk_generic "I see..."
    uk_generic "So that’s how it is, huh."
    emi "(He seems to be taking this well.)"
    emi "(Is it because he's lived a lot longer than me?)"
    brio "I didn’t expect to end up anywhere like this."
    brio "But in the blink of an eye..."
    "He sinks into his seat, deep in thought."
    ingram "If you're okay with it, would you like to share your story?"
    ingram "It might help air out whatever is weighing on your mind."
    "[ch1_name] hesitates for a moment."
    brio "...I was a guitar luthier."
    brio "My grandfather raised me, and he was a guitar luthier himself."
    brio "His workshop was my playground. I would spend all my time there, watching him work his craft."
    brio "Along the way, he sparked my musical passion as well."
    brio "He was well known for his craftsmanship."
    brio "Although he only had a humble workshop and preferred to keep on the down low, everyone in our area always wanted a guitar from him."
    brio "His personal guitar was his best work. He'd tell me all about the details he put into it, and how it sounded when he strummed away."
    "You notice his hands tighten around his cup."
    brio "Unfortunately, it was lost in a fire before I was born."
    brio "When I was diagnosed with pancreatic cancer this year, I figured I had time for one last build."
    brio "So I decided to recreate that guitar for his death anniversary."
    brio "But it's difficult when all you have are a few old photographs and journal entries to go off of."
    brio "I matched the wood. The shape. The bracing."
    brio "Everything should've matched my grandfather's notes."
    brio "But when it came time to apply the lacquer…"
    brio "I couldn’t do it."
    brio "You can always remake wood parts, but color’s permanent."
    brio "One mistake and you can’t take it back."
    brio "And I didn't have time to make another guitar."
    brio "I kept going back and forth on different finishes."
    brio "I thought, 'Oh, I'll make a decision tomorrow.'"
    brio "After more testing. After more experimenting."
    brio "But that tomorrow never came."
    brio "Eventually, my grandfather’s death anniversary passed."
    brio "Then the cancer spread."
    brio "By the time I was hospitalized, I couldn’t even hold the instrument anymore."
    "He exhales slowly."
    brio "But dying wasn’t the hard part. Leaving the guitar unfinished was."
    "You feel a tight ache in your chest."
    emi "(All that work and effort... he was so close to his goal.)"
    emi "(But at the last moment, he hesitated...)"
    emi "(Wouldn't his grandfather have been proud of whatever he poured his heart into?)"
    "After finishing his latte, [ch1_name] sets the cup down carefully."
    brio "Thanks for listening."
    brio "Guess that’s all I’ve got left to say, really."
    emi "..."
    emi "...Let us help you carry it a little further."
    brio "Sorry?"
    emi "Just before you move on, you'll get another chance, with us as your spirit guides!"
    emi "Isn't that right, Ingram?"
    "Ingram nods, and [ch1_name]'s eyes widen."
    brio "Is that true? Can I really?"
    ingram "That is what spirit guiding is all about."
    brio "I thought that was more about revisiting a happy memory."
    ingram "It depends on the person."
    ingram "Their final memory can revisit a happy one, or be another chance to fix a lifelong regret of theirs."
    ingram "If you're set on what you want your final memory to be, then follow me."
    scene blank with bgwipe
    scene sweven_mirror with bgwipe
    show ingram with dissolve
    "You arrive at the Sweven Mirror with [ch1_name] and Ingram."
    "Ingram begins the spirit guiding process, and you watch as [ch1_name] steps into the mirror."
    "A warm light envelops him. Soon, he vanishes from sight."
    "After he disappears, Ingram turns to you."
    "Ingram explains that since this is the first time you'll be actively involved in spirit guiding, he'll help walk you through the process."
    "He explains the importance of being present and mindful during spirit guiding."
    "That they are there to help the customer find closure and peace."
    "He also reminds you that things don't always go as planned."
    ingram "Don't beat yourself up if you don't achieve that goal."
    ingram "If you're ever confused on what to do, just step aside and try mentally calling on me for guidance."
    ingram "I'll still be there, watching over you."
    "You nod, taking in Ingram's words."
    "With that, Ingram prompts you to step into the mirror to begin spirit guiding."
    emi "(Alright, here goes nothing...!)"
    scene swevenlight with swevenwipe_cw
    pause(0.5)
    scene blank with Fade(0.75, 1.0, 0.75)
    return