label nuzzle_arm:
    "You gently nuzzle against [ch1_name]'s arm, pressing close for warmth."
    "Your feathers brush softly against his sleeve."
    emi "Chirp..."
    emi "(He looks so tired...)"
    brio "...Ah."
    "He lets out a slow breath he didn't realize he was holding."
    brio "You're warm. And so full of life."
    "He shifts slightly, careful not to disturb you."
    "One hand comes to rest near you, hovering for a moment before gently stroking your feathers."
    brio "Thank you."
    brio "You don't rush me. I appreciate that."
    emi "(Is that a good thing...?)"
    emi "(Does... this help?)"
    "For a while, the two of you stay like that."
    "The room is quiet except for the ticking of the clock and the distant hum of the city outside."
    "Eventually, [ch1_name]'s gaze drifts back to the list of lacquer names."
    "His fingers tighten slightly around the paper."
    brio "I just need a little more certainty."
    brio "This isn't something I can afford to get wrong."
    emi "Chirp..."
    emi "(He's thinking again...)"
    "He carefully lifts you and sets you a little closer to the window."
    brio "There. You'll get better light there."
    "He returns to his desk, pencil already moving."
    "More names are added."
    "More question marks."
    brio "I think I'll test a few more brands. Just to be safe."
    emi "(He looks calmer...)"
    emi "(But he hasn't moved any closer to the guitar.)"
    emi "(Will he find an answer...?)"
    scene blank with bgwipe
    scene workshop with bgwipe
    show brio with dissolve
    "Time passes."
    "The list of lacquer brands has grown longer."
    "So have the test swatches."
    "But the guitar remains untouched."
    brio "Almost there..."
    brio "I just need to narrow it down."
    "His hand trembles as he sets the pencil down."
    show brio at startle
    "He presses a fist to his mouth, coughing hard."
    show brio at startle
    emi "Chirp!"
    emi "(That sounded bad!)"
    "[ch1_name] waves a hand dismissively, forcing a weak smile."
    brio "It's fine."
    brio "Just overdid it today."
    "You could tell his time was near. He tried to hide it, but you managed to catch the blood on his palm."
    emi "([ch1_name]...)"
    emi "(His grandfather means so much to him, but the pressure is preventing him from finishing...)"
    scene blank with bgwipe
    scene hospital with bgwipe
    "..."
    "The smell of antiseptic fills the air."
    show brio with dissolve
    "[ch1_name] lies in a hospital bed, an IV attached to his wrist."
    "The workshop feels very far away."
    emi "(I followed him here...)"
    emi "(I didn't want him to be alone.)"
    "You sit at the window sill, chirping to catch his attention."
    "[ch1_name]'s eyes flutter open when he hears you."
    brio "...You came, little one."
    emi "Chirp..."
    "A faint smile tugs at his lips."
    brio "I'm glad."
    brio "I thought I'd have more time."
    brio "Funny how I kept saving things for later."
    "He turns his head slightly, staring at the ceiling."
    brio "There were so many good options."
    brio "I just... didn't know which one was right."
    emi "(...)"
    brio "I... at least, I'll see him again soon."
    "[ch1_name]'s hand slowly lifts, weak but deliberate."
    "He reaches toward you."
    "You hop closer, letting him gently brush your feathers one last time."
    brio "Thank you...for staying."
    brio "Even when I couldn't move forward."
    "His voice trembles. You could barely make out what he's saying."
    brio "It's time to go home now."
    brio "I'm tired, so I think I'll sleep for a bit."
    brio "I'll see you later, little one."
    "His breathing slows."
    "The tension in his face eases."
    "He smiles—soft, peaceful."
    emi "Chirp chirp..."
    emi "(Rest in peace [ch1_name]...)"
    scene white with dissolve
    pause(0.5)
    return