label reaching_out:
    "You extend a wing towards [ch1_name], hoping to offer some comfort."
    "However, your wing is a lot bigger than you anticipate and you knock over his cup of tea."
    "The piping hot liquid splashes all over, snapping [ch1_name] out of his thoughts."
    brio "Whoa!"
    "[ch1_name] quickly pulls back, startled by the sudden splash."
    emi "(Oh no! The tea!)"
    "[ch1_name] hurriedly grabs a cloth and cleans up the mess, trying to salvage all the papers on his desk."
    emi "Chirp..."
    emi "(I'm sorry for the mess...)"
    emi "(I just wanted to comfort him, was that so bad?)"
    "As he sifts through the stack of papers, trying to see what was ruined, a photograph falls to the ground."
    emi "(Huh...?)"
    emi "(Is that [ch1_name] when he was younger?)"
    "Show an aged photo of a young boy and his grandfather standing in front of a luthier shop."
    emi "(Thank goodness it didn't get caught in the spill! This looks like an important keepsake.)"
    "You grab the photo with your beak and hand it back to [ch1_name]."
    brio "This... why is this here? I thought it was..."
    brio "No, I took it out when I got diagnosed..."
    "[ch1_name]'s eyes well up with tears as he clutches the photo tightly."
    brio "I remember... this was back when I was in middle school."
    brio "I was so confused about what high school to apply to. I didn't even know what I wanted to do in life."
    brio "When I came home from school one day, I asked my grandfather about his work as a luthier."
    brio "He told me that he followed his passion for music and craftsmanship, and that made him happy."
    brio "He taught me these things come from the heart."
    brio "Whether it be music or making instruments, it's about sharing a part of yourself."
    brio "That was when I decided to become a luthier."
    "He stands there silently for a moment."
    "With a deep sigh, he recollects himself and looks at you with a grateful smile."
    brio "...Thank you, little one. You've helped me remember something important."
    emi "Chirp chirp!"
    emi "(The light's back in his eyes!)"
    brio "I think... I think I know how to finish this guitar now."
    "[ch1_name] grabs the work-in-progress from the wall and heads for the door."
    "His face is glowing, rejuvenated by a newfound determination shining through."
    brio "I'll be back, little one. There's work to do."
    "You watch as he leaves to finish off the guitar."
    scene blank with bgwipe
    scene workshop with bgwipe
    show brio with dissolve
    brio "It's... it's finished."
    "[ch1_name] admires the final product. It's a beautifully crafted guitar."
    emi "Chirp!"
    "He pets you with a brief gesture and heads over to the window."
    "You follow suit, watching as he tunes the guitar and gets ready to play it."
    "He glances at the calendar, with today's date circled in red."
    brio "Today marks the 30th anniversary since he passed away."
    brio "But I still remember him just as well as ever."
    brio "...Would you like to hear an old song, little one?"
    emi "Chirp!"
    "As [ch1_name] strums the guitar, a rich resonant tone fills the air."
    "You listen as he plays away, even mixing in some humming and lyrics here and there."
    emi "(What a kind sounding guitar. It really suits him.)"
    emi "(I'm glad he was able to finish it in the end.)"
    "You feel warm seeing [ch1_name]'s face in peace as he strums away."
    emi "(It's truly his guitar now.)"
    emi "(I bet his grandfather would be proud of him.)"
    scene swevenlight with swevenwipe_ccw
    pause(0.5)
    scene white with Dissolve(0.75)
    scene sweven_mirror with Dissolve(1.5)
    show ingram with dissolve
    ingram "Welcome back. You must be exhausted by now."
    emi "Yeah wow, that was... something."
    ingram "You did well. It's not easy experiencing the struggles of other people."
    emi "Thanks. It was fulfilling though."
    emi "Aa frustrated as I am about not being able to do anything about his pain, I'm glad he was able to finish the guitar in the end."
    ingram "Yes, I felt it. His feelings when he moved on."
    ingram "Now he can rest in peace."
    "Ingram smiles, then turns back on the path to the cafe."
    ingram "Well then, everything's finished. Let's head home."
    emi "Oh my god, yes please! I can't wait to get to bed."
    hide ingram with dissolve
    "Ingram heads down the trail as you stare at the mirror one last moment."
    show white with dissolve
    hide white with dissolve
    emi "...Huh?"
    emi "What's this...?"
    "A pocket of light pops out of the mirror, drifting ever so slowly towards you."
    "You reach out and grab the ball of light, revealing a photograph."
    "Show the photo of young [ch1_name] with his grandfather. This will be one of the achievements you can unlock for this game & a requirement for Ingram's true ending."
    emi "What's this doing here? Shouldn't this have disappeared with [ch1_name]'s memories?"
    ingram "[emi_name], is everything okay?"
    emi "Huh, oh yeah! It's nothing, I'm coming!"
    "You hide the photo and chase after Ingram, who is already a considerable distance away."
    #TODO: Add bool variable and set to True to indicate that ch1 was satisfied
    return