label about_ingram:
    emi "Ingram, I'm curious about something."
    ingram "Of course, what's on your mind?"
    emi "I was just wondering. . .is there nobody else working here? Is it really just you taking on everything?"
    ingram "Yes, that's right."
    emi "Don't you ever get tired or burned out?"
    emi "Earlier, you said it comes down to finding the right rhythm or being organized. . ."
    emi "But at some point, there has to be a limit, no?"
    narrator "Ingram shakes his head, his gaze shifting slightly."
    ingram "It's one of the perks of being a spirit guide."
    ingram "You see, my constitution is a bit different than yours."
    ingram "As you've seen so far, there's a lot of responsibility that comes with spirit guiding, especially since it's on a regular basis."
    ingram "My powers allow me to be able to keep up with everything."
    emi "Does that mean you never get tired then?"
    ingram "Well, think of it this way. It still requires effort to get all these tasks done, but I don't expend as much energy as a regular person would."
    ingram "So with that being said, it's not often that I get that tired."
    emi "I see. . .well if you say so, then I'll take your word for it."
    emi "But that doesn't completely answer the question of why there's no other staff here. You've never thought about enlisting someone to divide up the work?"
    narrator "Ingram sets down his cloth, leaning casually against the counter. There's a contemplative look on his face, as if weighing his words carefully."
    ingram ". . .I could never choose to burden someone with that responsibilty."
    ingram "People don't come to Nobaros of their own accord. Why would they want to work while they're here?"
    ingram "It just doesn't sit well with me to force these responsibilities on someone else."
    emi "Then what about me? I asked you if I could help out and now here I am, doing exactly that."
    ingram "Well, it's not that I'd reject the help if it's offered."
    ingram "But you're the first person to ever ask."
    emi "Really? Not a single person?"
    ingram "Really."
    ingram "That's why I was surprised when you told me you wanted to help out."
    narrator "Ingram looks at me with a steady gaze, his voice devoid of any doubt."
    narrator "An uncomfortable feeling stirs within me as I realize the sincerity in Ingram's words. It's disheartening to think that no one ever thought to offer some help around the cafe."
    emi "(Are people really that heartless. . .?)"
    emi "(. . .No, that's not right.)"
    emi "(It's not that they're heartless. Most people would be too focused on recovering their memories. Working at the cafe wouldn't normally cross their minds.)"
    emi "(I can't blame them, but still. . .)"
    emi "(. . .It's a good thing that I'm here. Although it's weird to think that, considering my circumstances.)"
    narrator "I steal a glance at Ingram, who notices my silence."
    ingram "Are you okay? You got silent all of a sudden."
    ingram "I hope you're not regretting your decision."
    ingram "But if you're having second thoughts, you should let me know and I can-"
    emi "N-no, there's no need for that!"
    emi "I was just thinking to myself a bit."
    ingram "Is that so? A penny for your thoughts?"
    emi "Well. . .I was just thinking about how glad I am to be here, to help lighten your load a bit."
    narrator "Ingram's eyes widen, clearly taken aback by my response. There's a subtle shift in his expression, a brief moment of surprise that quickly fades. As soon as I register the change, he resumes the same smile as before."
    ingram "That'll depend on your capabilities. If you manage to learn things quickly, then maybe that might be true."
    ingram "You'll just have to work extra hard in that case."
    emi "Yes, of course! I made sure to do exactly that when I was finishing the tasks you assigned to me earlier."
    return
