label milk_and_honey:
    narrator "I grab the bottle of milk, craving its coolness against my warm skin after a bath."
    emi "(I'll just savour this moment! If someone wants milk later, I'll apologize and go buy more with Ingram sometime. . .)"
    emi "(Let's find something to pour this into first. . .)"
    narrator "As I search around for a mug, I'm reminded of the warm milk that Ingram prepared for me a while back."
    emi "(Hmm, warm milk doesn't sound that bad. The milk he made that time felt extra comforting, it'd be the perfect bedtime drink!)"
    narrator "I place a mug on the counter, and begin hunting for a saucepan to heat the milk."
    narrator "As I begin digging through the pots and pans in one of the bottom cupboards, I spot Ingram entering the kitchen out of the corner of my eye."
    show ingram with dissolve
    ingram ". . .Emi? What are you up to?"
    emi "Oh, Ingram! Good timing, I was just thinking of  having some milk before bed!"
    emi "I'm looking for a saucepan to make the sweet milk you made last time. Do you know where it might be? I can't seem to find it."
    ingram "Ah, good timing. I was just craving some spiced milk myself."
    emi "Spiced milk? That sounds good, can I try some?"
    ingram "Sure, I can make some for you too."
    narrator "Ingram crouches next to me and rummages through, effortlessly pulling out a saucepan out of nowhere."
    ingram "Here's the saucepan by the way, it was just pushed all the way in the back corner there."
    emi "What? How'd you find that so quickly? I didn't even see it!"
    narrator "Ingram shrugs as we stand to our feet, placing the saucepan on the stovetop."
    ingram "Just a hunch. If you weren't able to find it right away, then it was likely hidden somewhere deeper in there."
    emi "(. . .Does his spirit guide powers give him magical investigation skills too? What is this sorcery?)"
    narrator "I grab another mug for Ingram as he pours the remaining milk into the saucepan and turns on the heat."
    emi "So what's this spiced milk drink you're making?"
    ingram "That's the idea. By infusing a variety of spices with milk, you'll get an interesting twist that slightly resembles chai tea."
    emi "Oh, that sounds good! So almost like a chai milk tea then?"
    ingram "You can think of it that way. Just take out the tea part and that's pretty much what it is."
    emi "Okay, I look forward to it! What spices do you need? I can go grab them while the milk is still boiling."
    ingram "Sure, can you grab me some dried chili peppers, black pepper and cayenne?"
    emi ". . ."
    emi ". . .Are you trying to put me to sleep forever?"
    narrator "Seemingly amused by my reaction, he smirks with a mischievous glint in his eyes."
    ingram "Here, why don't you watch the pot? I'll go grab them myself."
    narrator "Ingram hands me a wooden spoon as he pulls out a number of spice jars from the pantry. Once the milk starts simmering, he returns and sets them nearby on the countertop."
    emi "(Cloves, cinnamon, ginger, nutmeg, and vanilla. Huh, there's more spices than I expected.)"
    narrator "As I slowly stir the milk, Ingram takes a spoon and carefully measures out each spice, before plopping them into the pot."
    narrator "With each addition, the milk's white colour turns into a darker shade of speckled brown, and the exotic aroma from the pot grows a tad more complex."
    narrator "In a matter of minutes, the milk infuses with the spices and Ingram pours it into the mugs. Swirling trails of steam emerge from the drink, tempting me to dig right in."
    ingram "Wait, it's not ready yet."
    emi "Huh?"
    narrator "Ingram stops me just as I reach for one of the mugs, halting me right in my tracks."
    narrator "With a jar of honey in hand, he stirs a dollop into each of our mugs, the golden texture disappearing into the creamy milk."
    narrator "Once the honey is dissolved, he passes a mug over to me."
    ingram "It wasn't sweetened yet. I just mixed some honey in."
    emi "Oh, thank you."
    ingram "Of course, I wouldn't want you spitting it out all over the kitchen."
    emi "Hey, I wouldn't do that! You went through all that effort of preparing it for me after all."
    ingram "Okay, but you'd make a face for sure, knowing your sweet tooth."
    emi ". . .I can't deny that."
    ingram "I thought so."
    narrator "Ingram smiles as he tastes his drink. I follow suit, bringing the mug to my lips. After blowing a bit, I take a generous sip."
    narrator "The warmth of the milk envelops my taste buds, carrying with it the rich, earthy notes of cloves."
    narrator "There's a subtle sweetness from the cinnamon and honey, and a gentle heat from the ginger. A hint of nutmeg adds depth to the flavour, while the vanilla brings it all together with its delectable essence."
    emi "(So warm! It feels so cozy.)"
    narrator "I smile in delight, pleased by my choice to heat the milk instead of drinking it cold."
    emi "Thank you for teaching me how to make this, Ingram. You always know how to make such comforting drinks, they really warm me up."
    ingram "Good, that's another drink you can make if you ever need a pick-me-up."
    narrator "Ingram falls quiet, and we continue drinking."
    narrator "As I stare down at my mug, I'm reminded of all the ways Ingram has helped me since arriving in Nobaros."
    narrator "Although the currently circumstance is a heavy topic to brood over, I find myself growing accustomed to this place."
    emi ". . .Thank you."
    ingram ". . .Another thanks? You just said that."
    emi "No, I meant to say. . .thank you for everything so far.  I just wanted to say that I really appreciate all the help you've given me."
    ingram ". . ."
    ingram "It's no problem. What kind of spirit guide would I be if I left you to deal with this all on your own?"
    ingram "It's my responsibility to help you become comfortable here."
    narrator "He takes another sip of his milk, another moment of silence settling between us."
    narrator "Although his words brush off the sentiment as another part of his duties, the surprised look in his eyes gives him away."
    ingram ". . .Actually, I should be the one thanking you."
    emi "Thanking me? For what?"
    narrator "My heart skips a beat as I wait for his answer. He hesitates, his expression thoughtful, before he speaks again."
    ingram "For helping me. In more ways than you think."
    ingram "I'm sure you must've noticed but. . .it's been kind of weird, having to work with someone else for a change."
    ingram "Sure, there's the occasional vagabond during spirit guiding, but there's not much interaction happening there."
    ingram "Nobody goes into it as enthusiastically as you. And you always serve customers with a smile on your face at the cafe."
    ingram "I'm used to handling all that stuff alone, but you take it a step further and add a touch of humanity to it. And for that, I'm thankful for your presence."
    emi ". . .I see. I'm glad to hear that."
    narrator "I can't help but smile at Ingram's words, feeling a warm sense of satisfaction wash over me. It's humbling to hear how much of an impact I've had on him, and that my actions are actually helping."
    narrator "We savour the rest of our drinks in peace, our voices disappearing into the dead of night as we bask in the moonlight shining through the window."
    scene blank with bgwipe
    scene yuugen_common with bgwipe
    show ingram with dissolve
    emi "Have a good night, Ingram. Thanks again for the milk."
    ingram "You too. Remember that we have another pastry training session tomorrow, so be sure to get some rest."
    narrator "With a final smile, the both of us head up to our rooms to retire for the night."
    return
