label around_town_intro:
    scene nobaros_town with bgwipe
    "The buzz of people swarming about fills your ears."
    show ingram with dissolve
    ingram "Welcome to the town of Nobaros."
    ingram "It's a little busy at this time of day."
    ingram "Take care to watch your step."
    "You walk just a few steps behind Ingram."
    "As you continue on, numerous people recognize him and say hi."
    uk_generic "Ingram! Good to see you, out for some chores today?"
    "A boisterous lady's voice calls out from behind a booth."
    ingram "Haha, you know how it is. Just the usual duties."
    uk_generic "Always so hardworking, aren't ya?"
    uk_generic "While I've got ya here, don't forget what I asked for hm?"
    uk_generic "I can't do my fortune telling without it!"
    ingram "Ah yes, I'll be sure to get you some before the festival."
    "He leaves her with a nod, and the two of you walk along."
    "In the corner of your eye, you spot a massive construction project."
    "Several workers surround the scene, rushing about as if trying to meet a deadline."
    "You tried to make sense of what it is they might be building, but to no avail."
    "Just then, you pick up on a delicious scent."
    "You felt your stomach rumble."
    ingram "Hungry?"
    "Ingram seemed to notice as well."
    ingram "We can go grab something to eat at the marketplace."
    ingram" They have plenty of good options there. And I have some vendors to talk to there too."
    "You nod and scurry along, following him like a lost child."
    scene blank with bgwipe
    scene nobaros_marketplace with bgwipe
    show ingram with dissolve
    "The smell of piping hot food fills the air, much more intense than before."
    "Ingram asks if there's any particular food you're craving."
    "Images of various items flash through your mind."
    "Skewers, yakisoba, takoyaki, etc..."
    "You could feel yourself drooling by the minute."
    "You shake your head."
    emi "No, anything sounds good right now. I'll go with your choice."
    "He ponders for a moment."
    ingram "Alright, I know just the place."
    ingram" Are you okay to wait in line for a bit?"
    "You nod, and Ingram takes you to a stall selling onigiri."
    "He explains that the onigiri vendor here is one of the most popular stops."
    "He asks you what filling you'd like and orders accordingly."
    hide ingram with dissolve
    "As the two of you wait for the onigiri to be made, you can't help but scour the crowd and soak in the atmosphere."
    "Your eyes land on a particularly noisy stand. There's a young man eagerly shouting to attract customers."
    emi "(That stand also has a lot of people... What are they selling?)"
    "You shift your head to get a better look, seeing several skewers of candied fruit on display."
    emi "(Those look pretty. I almost want a few for myself...)"
    uk_kai "Excuse me!! Can I get 8 of those tanghulu please?"
    show kai at left
    show annelise at right
    with dissolve
    "A voice cuts through the crowd, coming from a pair standing in line."
    uk_annelise "W-wait, isn't that too much...?"
    uk_kai "It's alright, I'm ordering some for us!"
    uk_kai "3 for me, 3 for you!"
    uk_annelise "But what about the remaining ones...?"
    uk_kai "We can save those for later, when we feel like eating them!"
    uk_annelise "Oh, I see...! So we'll get to enjoy them for entire day then!"
    uk_kai "Heheh, exactly!"
    hide kai
    hide annelise
    with dissolve
    "The two get their tanghulu and head off elsewhere, happily snacking away."
    emi "(That's a lot... must be nice. I'd do the same thing if I could.)"
    "You smile, fantasizing of snacking away endlessly on tanghulu."
    show ingram with dissolve
    ingram "That took a bit, sorry for the wait. Let's find a spot to sit and enjoy these."
    "The two of you nab a table right as a family leaves. The both of you enjoy a small but fulfilling lunch."
    "As you munch away, Ingram asks if you have any questions so far."
    "(Maybe have several core questions as choices here?)"
    emi "Everyone here... are they all people who have passed away?"
    ingram "Well, yes and no. Sort of."
    "Ingram explains that whenever someone passes onto the afterlife, a new spirit is born in Nobaros."
    "He mentions the notion of a life for a life. When someone's journey is done, their lived experiences become the foundation of a new spirit's journey."
    "As a result, the spirits take on the appearance of the human they were born from."
    "But to clarify, they only borrow their appearance. They are not the person themselves."
    "Therefore, all the townspeople around them are actually just normal spirits."
    "You are taken aback, surprised considering how human-like the spirits seem."
    "You would've thought that mystical beings like spirits would take on a more... unique appearance."
    "But you thought it was cool that there was a sort of cycle at play here."
    ingram "Alright, I think that's it for lunch then. Let's head out."
    emi "Huh? Where are we going?"
    ingram "Do you remember what I mentioned earlier about having errands to run?"
    ingram "We'll be visiting several merchants to pick up some ingredients I ordered a while ago."
    ingram "Then after that, you'll get to see where I work."
    scene blank with bgwipe
    return