label around_town:
    scene nobaros_town with bgwipe
    "The buzz of people swarming about fills your ears."
    show ingram with dissolve
    ingram "Welcome to the town of Nobaros."
    ingram "It's a little busy at this time of day."
    ingram "Take care to watch your step."
    "You walk just a few steps behind Ingram."
    "As you continue on, numerous people recognize him and say hi."
    uk_generic "Ingram! Good to see you, out for some chores today?"
    "A boisterous lady's voice calls out from behind a booth."
    ingram "Haha, you know how it is. Just the usual duties."
    uk_generic "Always so hardworking, aren't ya?"
    uk_generic "While I've got ya here, don't forget what I asked for hm?"
    uk_generic "I can't do my fortune telling without it!"
    ingram "Ah yes, I'll be sure to get you some before the festival."
    "He leaves her with a nod, and the two of you walk along."
    "In the corner of your eye, you spot a massive construction project."
    "Several workers surround the scene, rushing about as if trying to meet a deadline."
    "You tried to make sense of what it is they might be building, but to no avail."
    "Just then, you pick up on a delicious scent."
    "You felt your stomach rumble."
    ingram "Hungry?"
    "Ingram seemed to notice as well."
    ingram "We can go grab something to eat at the marketplace."
    ingram" They have plenty of good options there. And I have some vendors to talk to there too."
    "You nod and scurry along, following him like a lost child."
    scene blank with bgwipe
    scene nobaros_marketplace with bgwipe
    show ingram with dissolve
    "The smell of piping hot food fills the air, much more intense than before."
    "Ingram asks you if you'd be comfortable waiting as he leaves to deal with some errands."
    "You nod, taking a seat at a nearby table."
    "Before leaving, Ingram asks if there's any particular food you're craving."
    "Images of various items flash through your mind."
    "Skewers, yakisoba, takoyaki, etc..."
    "You could feel yourself drooling by the minute."
    "You shake your head."
    emi "No, anything sounds good right now! I'll go with whatever's popular!"
    hide ingram with dissolve
    "With a nod, Ingram leaves."
    "You sit patiently, observing the townpeople around you."
    "Your eyes scour the food vendors."
    emi "(Whoa! That stand has a long line up!)"
    "Your eyes land on a particularly flashy stand. It's adorned with fruit skewers all over."
    emi "(Those look good too... Maybe I'll have that for dessert after.)"
    uk_kai "Excuse me!! Can I get 8 of those tanghulu skewers please?"
    show kai at left
    show annelise at right
    with dissolve
    "A voice cuts through the crowd, coming from a pair standing in line."
    uk_annelise "W-wait, isn't that too much...?"
    uk_kai "It's alright, I'm ordering some for us!"
    uk_kai "3 for me, 3 for you!"
    uk_annelise "But what about the remaining ones...?"
    uk_kai "We can save those for later, when we feel like eating them!"
    uk_annelise "Oh, I see...! It's like having two snacktimes in one day."
    uk_annelise "That's a good idea!"
    uk_kai "Heheh, right? I've got you covered!"
    hide kai
    hide annelise
    with dissolve
    "The two get their skewers and head off elsewhere, happily snacking away."
    emi "(Whoa, he ordered a lot...)"
    emi "(Though I feel like I'd probably do the same thing myself right now.)"
    "You smile to yourself, giddy about the idea of snacking away as you please."
    show ingram with dissolve
    ingram "Sorry for making you wait. That took a bit longer than I expected."
    "Ingram returns with a few bags, full of what seems to be groceries."
    "He digs through one of them and hands you some onigiri."
    "He explains that the onigiri vendor here is one of the most popular stops."
    "You thank him for the food and the both of you enjoy a small but fulfilling lunch."
    "As you munch away, Ingram asks if you have any questions so far."
    "(Maybe have several core questions as choices here?)"
    emi "Everyone here... are they all people who have passed away?"
    ingram "Well, yes and no. Sort of."
    "Ingram explains that whenever someone passes onto the afterlife, a new spirit is born in Nobaros."
    "He mentions the notion of a life for a life. When someone's journey is done, their lived experiences become the foundation of a new spirit's journey."
    "As a result, the spirits take on the appearance of the human they were born from."
    "But to clarify, they only borrow their appearance. They are not the person themselves."
    "Therefore, all the townspeople around them are actually just normal spirits."
    "You are taken aback, surprised considering how human-like the spirits seem."
    "You would've thought that mystical beings like spirits would take on a more... unique appearance."
    "But you thought it was cool that there was a sort of cycle at play here."
    ingram "Alright, I think that's it for lunch then. Let's head out."
    emi "Huh? Where are we going?"
    ingram "Well, I've gotta put these groceries somewhere right?"
    ingram "We'll be heading to where I work."
    scene blank with bgwipe
    return