label ingram_intro:
    "Think about the idea of memories."
    "How important they are to us."
    "Imagine those you love and cherish."
    "Those relationships are special because of the memories you share."
    "But there are relationships we fear because of memories as well."
    "Whether we have joyful or tragic memories, they define us as a person."
    "Memories are what write our story."
    "And everyone has a story. (This is the key theme of Nobaros Cafe)."
    "But what happens if those memories cease to exist?"
    "Is your story continued as a new chapter?"
    "Or is it an entirely new story overall?"
    "..."
    scene ingram_intro with fade
    "There appears to be a conversation between two parties."
    "A has come to B for something."
    "B notices how hurt and bruised A's soul has become from his rough experiences."
    "At heart, A is kind and gentle. But his memories carry pain and suffering."
    "This pain is way beyond what A's heart can handle. He's tired and weary."
    "And so, this is the reason why A has come to B for help."
    "There's a quiet understanding between A & B as to what kind of help he wants."
    "B reminds A that everything comes with a price."
    "It is then implied that A is asking B to wipe his memories for some reason."
    "B reminds A that he won't lose just the pain, but all his happy moments too."
    "He asks A one more time if he really wants to go ahead with this decision."
    "It is unclear how A reacts, but he goes through with the decision."
    "Seeing A's resolve, B decides to help A."
    "Before wiping his memories, B hopes that someday, A will be able to face his past and properly move on."
    "But for now, B simply instructs A to close his eyes and breathe."
    "He wishes A sweet dreams before doing what he needs to do."
    scene blank with fade
    "B's voice disappears, waiting for the day they meet again."
    "..."
    return