label nobaros_intro:
    scene white with fade
    "The voices slowly fade away and are replaced by a gust of wind."
    "The wind spurs the tinkling of windchimes in the distance."
    scene yuugen_common with dissolve
    "Sunlight lands on your face, stirring you from sleep."
    "You regain consciousness, sitting up from the couch you're currently on."
    "It feels as if you've been asleep for centuries, yet your body is as light as a feather."
    "You wonder where you are. The scene in front of you is unfamiliar."
    "Questions start racing through your mind, only making you more confused."
    "Did you fall asleep somewhere? No, that doesn't make sense."
    "What happened here exactly?"
    "Why couldn't you remember anything?"
    "No matter how hard you tried, your head remained blank."
    "You begin going over the worst case scenarios."
    "Your breathing quickens and you could feel yourself getting more stressed."
    "Suddenly a voice interrupts your thoughts."
    uk_ingram "Are you okay?"
    show ingram with dissolve
    "You look up, unexpectedly meeting a pair of aqua blue eyes."
    "The guy looks at you with furrowed brows."
    uk_emi "Who are you? Where am I??"
    uk_ingram "First, take a deep breath. Let's clear your thoughts and then I'll explain."
    "You do as he says, clearing your head more with each breath."
    "He smiles once you've gathered yourself."
    "Somehow, he gave off a strange sense of safety and comfort. You couldn't explain why."
    "He sits at an ottoman a fair distance away from you, trying not to spook you."
    "He introduces himself as Ingram, and that you are currently in a world called 'Nobaros'."
    "Nobaros is a world where people's spirits go before passing onto the afterlife."
    "And he helps coordinate that spirit guiding process as the 'spirit guide'."
    ingram "You must be feeling pretty lost right now."
    ingram "Do you remember anything? Like your name for starters?"
    uk_emi "(My name...)"
    call pickName
    emi "My name is [emi_name] Auclaire."
    "He nods, asking if there's anything else."
    "Unfortunately, that's all you're able to answer. You anxiously ask him if you're dead, based on his explanation."
    "He chooses his wording carefully, trying to reassure you that you aren't necessarily done for."
    "In fact, you are a special case called a 'vagabond'."
    "Vagabonds are those whose spirits are caught between life and death."
    "He uses the example of being in a comatose state after being caught in an accident."
    "Vagabonds tend to arrive in Nobaros as amnesiacs, which is exactly your situation."
    "He keeps his explanation simple so as to avoid overwhelming you."
    "You nod along. Although you understand his words, it's hard to grasp the situation you're in."
    "You still can't help the anxiety in your heart, even though you should be grateful that you're still alive."
    "Ingram sees the conflict in your eyes."
    "He changes the topic, offering you to come with him to see what Nobaros is like."
    "He'll just be doing some errands around town. Experiencing things for yourself might help you to adjust."
    "You hesitate, but decide to accept his offer. You're unsure of what to expect."
    "He nods, telling you that he'll be sure to keep you safe."
    "You look at his eyes again, feeling the odd sense of comfort from earlier."
    "You can't help but wonder what the town will be like."
    scene blank with bgwipe
    return