label nobaros_cafe_intro:
    scene cafe with bgwipe
    show ingram with dissolve
    ingram "Well then, here we are."
    "With the chime of a bell, Ingram leads you into a welcoming cafe."
    ingram "Welcome to Nobaros Cafe."
    "He proceeds to unpack all of the grocery bags with him."
    "There is a range of ingredients, from milk cartons to flavored syrups."
    "Ingram opens a bag, revealing freshly roasted beans."
    "As he fills a coffee grinder, you look around the cafe."
    "As comfy and inviting the layout is, you wonder where everyone is."
    "Ingram explains that the cafe is closed today for restocking."
    "Hence the reason why he had a bunch of errands to do around town."
    "Just then, he places a freshly brewed latte in front of you."
    ingram "Here. Consider it a welcome drink to Nobaros."
    "You stare in awe at the perfect rosetta on top as coffee fills the air."
    emi "Whoa, you made this? The latte art is so clean!"
    ingram "Comes with practice."
    "You take a sip of the latte, enjoying its warmth."
    "It was comforting, though bitter."
    ingram "What's wrong? Did you burn your tongue?"
    emi "Huh? Oh no, I just didn't expect it to be as bitter as it was..."
    ingram "Here, I can help with that."
    "You sat patiently as he pumps some syrup to your cup."
    "When you taste the drink again, the bitterness is now covered by the mellow taste of vanilla."
    emi "Mm! That's really good, thank you."
    "He smiles and proceeds to pull out a sponge cake from the cooler."
    emi "So wait, you're a barista then? I thought you were a guide of some sorts?"
    ingram "Well, you could say I'm both."
    ingram "When it comes to this place, I pretty much handle everything."
    "His hands move quickly as he slices up fresh fruit."
    ingram "I serve coffee and treats to anyone who stops by..."
    "He spreads a thick layer of cream over the cake, smoothing it with an icing knife before placing fruit on top."
    "In just a few moments, a beautiful dessert takes shape before your eyes."
    ingram "...But my real work is spirit guiding—helping people move on."
    emi "Spirit guiding... you mentioned that earlier."
    emi "What exactly does that mean?"
    "Ingram explains that spirit guiding is the process of giving people one last happy memory before they move onto the afterlife."
    "Whether they use that chance to relive a happy memory or fix a regret they've held their whole life is up to them."
    "As a spirit guide, he simply provides them the opportunity and helps them through the process."
    "You think the concept makes sense, but ask him about how it all happens."
    "Before he can answer, the soft chime of the front bell cuts through the air."
    "A man stands by the doorway, glancing around with visible confusion."
    uk_generic "...Huh? Where... am I?"
    "Ingram straightens, his expression softening instantly. He walks toward the man with calm, welcoming steps."
    ingram "Welcome to Nobaros Cafe."
    "The man blinks, clearly unsure how to respond."
    uk_generic "Nobaros...? I... I don’t remember coming here."
    ingram "That’s all right. You’re safe here. Please, have a seat."
    "Still looking uncertain, the man lets himself be guided to one of the counter stools."
    "Ingram moves with a quiet confidence, setting a menu before him."
    ingram "Here's our special drink menu. Feel free to pick whatever stands out to you."
    ingram "The drink you choose will reflect what your heart’s looking for."
    "Ingram returns behind the counter. You lean in, keeping your voice low."
    emi "So that man... is he a spirit? Or did he...?"
    "He nods, confirming your train of thought."
    ingram "Yes, he's passed on and will need spirit guiding."
    emi "How do you know?"
    ingram "Notice how disoriented he looks. He isn't really familiar with this place."
    emi "Couldn't he be a new spirit? Like the ones that are born after...someone passes on?"
    ingram "That's a fair point."
    ingram "Typically, new spirits are eager and enamoured by their surroundings."
    ingram "But not him. He's much too tense."
    "You understand what Ingram is getting at."
    "Out of the corner of your eye, you see the man rub his arm as he studies the menu."
    "You wonder why he's reading the menu so intensely."
    "Ingram seems to notice you getting antsy, and offers you a copy as well."
    "(Show a picture of the actual menu here for the player to read)"
    ingram "This is a spirit guiding menu. It's different from the one used to serve regular customers."
    ingram "As you can see, each drink is associated with a specific type of memory."
    ingram "Depending on what the customer chooses, the spirit guiding process is tailored to their memory accordingly."
    "Just then, the man calls out to Ingram, wanting to order a latte."
    "Witout skipping a beat, Ingram begins preparing the drink."
    "Each step is deliberate—the sound of beans grinding, the hiss of steam, the gentle pour of milk into a ceramic cup."
    "Then, he reaches for a small vial filled with a faintly glowing liquid. The light inside emits a soft aura, like liquid moonlight."
    "He tilts the vial, letting a few drops fall into the cup. The surface of the drink shimmers faintly, catching a soft glow as the essence dissolves."
    emi "What was that?"
    ingram "Essence from a Lunaria flower. It reacts to the truth in a person’s heart and helps bring their desired memory to the surface."
    "He slides the cup gently toward the man."
    ingram "Here you go. Take a sip, and tell me what it reminds you of."
    "The man wraps his hands around the cup, warmth spreading through his fingers as he brings it to his lips."
    uk_generic "...It tastes like... coffee from my kitchen. My wife used to brew it every morning."
    ingram "That sounds lovely. What was it like—those mornings with her?"
    "A small smile tugs at the man’s lips."
    uk_generic "Peaceful. She’d hum while she cooked, and I’d read the paper. It wasn’t anything special, but... it felt like home."
    ingram "I can imagine. It must've been pleasant having that sort of idyllic life."
    ingram "When was the last time you shared a morning like that?"
    "The man’s smile falters slightly."
    uk_generic "...Too long ago now."
    uk_generic "At one point, we were going through a divorce. A messy one."
    uk_generic "She and I got into an argument. And I said something I shouldn't have."
    uk_generic "Before I was able to apologize, she..."
    "The man chokes up."
    uk_generic "...There was an accident."
    uk_generic "...I've avoided coffee ever since. I thought I’d forgotten the smell of it."
    "Ingram’s voice softens even more, his tone both steady and compassionate."
    ingram "Then you’ve remembered something precious. Hold onto it, just for a while."
    "The man closes his eyes and recollects himself."
    ingram "...Would you like to speak to her once more?"
    "The man looks up in surprise."
    uk_generic "What do you mean?"
    ingram "I can help you revisit that memory. See her again, and say what was left unsaid."
    "The man hesitates, then nods slowly."
    ingram "Come then, follow me."
    scene blank with bgwipe
    return