label nobaros_cafe:
    scene cafe with bgwipe
    show ingram with dissolve
    ingram "Well then, here we are."
    "With the chime of a bell, Ingram leads you into a welcoming cafe."
    ingram "Welcome to Nobaros Cafe."
    "He proceeds to unpack all of the grocery bags with him."
    "There is a range of ingredients, from milk cartons to flavored syrups."
    "Ingram opens a bag, revealing freshly roasted beans."
    "As he fills a coffee grinder, you look around the cafe."
    "As comfy and inviting the layout is, you wonder where everyone is."
    "Ingram explains that the cafe is closed today for restocking."
    "Hence the reason why he had a bunch of errands to do around town."
    "Just then, he places a freshly brewed latte in front of you."
    ingram "Here. Consider it a welcome drink to Nobaros."
    "You stare in awe at the perfect rosetta on top as coffee fills the air."
    emi "Whoa, you made this? The latte art is so clean!"
    ingram "Comes with practice."
    "You took a sip of the latte, enjoying its warmth."
    "It was comforting, though bitter."
    ingram "What's wrong? Did you burn your tongue?"
    emi "Huh? Oh no, I just didn't expect it to be as bitter as it was..."
    ingram "Ah, so you prefer sweeter things then."
    ingram "Here, I'll help with that."
    "You sat patiently as he proceeded to add more syrup and milk to your cup."
    "When you taste the drink again, the bitterness is now covered by the mellow taste of vanilla."
    emi "Mm! That's really good, thank you."
    "He smiles and proceeds to pull out a cake from the cooler."
    emi "So wait, you're a barista then? I thought you were a guide of some sorts?"
    ingram "Well, you could say I'm both."
    ingram "I usually handle both barista and baker duties when managing this cafe."
    "He explains as he quickly chops up some fruit and quickly decorates the cake with cream."
    "Soon enough, the ordinary sponge cake turns into a beautiful looking product for sale."
    ingram "But my main job is spirit guiding and helping people pass on."
    "You ask him how he does that exactly, and what exactly is spirit guiding."
    "As he's about to explain, a bell chimes, signalling someone has entered the cafe."
    return