label nobaros_cafe:
    scene cafe with bgwipe
    show ingram with dissolve
    ingram "Well then, here we are."
    "With the chime of a bell, Ingram leads you into a welcoming cafe."
    ingram "Welcome to Nobaros Cafe."
    "He proceeds to unpack all of the grocery bags with him."
    "There is a range of ingredients, from milk cartons to flavored syrups."
    "Ingram opens a bag, revealing freshly roasted beans."
    "As he fills a coffee grinder, you look around the cafe."
    "As comfy and inviting the layout is, you wonder where everyone is."
    "Ingram explains that the cafe is closed today for restocking."
    "Hence the reason why he had a bunch of errands to do around town."
    "Just then, he places a freshly brewed latte in front of you."
    ingram "Here. Consider it a welcome drink to Nobaros."
    "You stare in awe at the perfect rosetta on top as coffee fills the air."
    emi "Whoa, you made this? The latte art is so clean!"
    ingram "Comes with practice."
    "You take a sip of the latte, enjoying its warmth."
    "It was comforting, though bitter."
    ingram "What's wrong? Did you burn your tongue?"
    emi "Huh? Oh no, I just didn't expect it to be as bitter as it was..."
    ingram "Ah, so you prefer sweeter things then."
    ingram "Here, I can help with that."
    "You sat patiently as he pumps some syrup to your cup."
    "When you taste the drink again, the bitterness is now covered by the mellow taste of vanilla."
    emi "Mm! That's really good, thank you."
    "He smiles and proceeds to pull out a sponge cake from the cooler."
    emi "So wait, you're a barista then? I thought you were a guide of some sorts?"
    ingram "Well, you could say I'm both."
    ingram "When it comes to this place, I pretty much handle everything."
    "His hands move quickly as he slices up fresh fruit."
    ingram "I serve coffee and treats to anyone who stops by..."
    "He spreads a thick layer of cream over the cake, smoothing it with an icing knife before placing fruit on top."
    "In just a few moments, a beautiful dessert takes shape before your eyes."
    ingram "...But my real work is spirit guiding—helping people move on."
    emi "Spirit guiding? How do you even do that?"
    "Before he can answer, the soft chime of the front bell cuts through the air. Someone’s just entered the cafe."
    return