label nobaros_cafe_intro:
    scene cafe with bgwipe
    show ingram with dissolve
    "With the chime of a bell, Ingram leads you into a welcoming cafe."
    ingram "Here we are. You can place the ingredients over there."
    "You quickly head over to the countertop, carrying a box of ingredients in your hands."
    "Ingram does the same, proceeding to immediately unpack everything."
    ingram "Thanks for helping me carry stuff. I had a lot to pick up today, so you saved me a trip."
    emi "It's no problem. So this is where you work?"
    ingram "That's right, welcome to Nobaros Cafe."
    emi "It's got a nice layout and everything. I like it already!"
    ingram "Glad to hear it."
    "You watch as Ingram arranges the ingredients on the counter."
    "There is a range of ingredients, from milk cartons to flavored syrups."
    "Ingram opens several bags, revealing freshly roasted beans."
    emi "That's a lot of beans. Do you go through them quickly?"
    ingram "Well it's a mix of different blends."
    ingram "For example, these beans have burnt caramel hints."
    ingram "While the other blends have fruity or nutty undertones."
    ingram "That being said, they do go fast, especially on busy days."
    "Ingram explains that the cafe is closed today for restocking."
    "As he fills a coffee grinder, you look around the cafe."
    "With how comfy and inviting the place feels, you wonder what it's like when filled with customers."
    "Just then, he places a freshly brewed espresso in front of you."
    ingram "Here. Consider it a welcome drink to Nobaros."
    emi "Whoa, you made this? It smells so good!"
    ingram "This is our signature house blend."
    ingram "Give it a try. See if you like it."
    "You take a sip, curious about the undertones."
    emi "(Oh wow, that's...)"
    "The warmth was comforting, though not quite what you expected."
    "You couldn't pick out any of the flavor hints Ingram mentioned. It was just..."
    ingram "What's wrong? Did you burn your tongue?"
    emi "Huh? Oh no, I just didn't expect it to be as bitter as it was..."
    ingram "Ah, that's okay, it takes a bit to develop a palate for espresso."
    ingram "Pass me your cup, I can help with the bitterness."
    "You sit patiently as he pours the espresso into a mug."
    "He also adds some syrup and steamed milk, pouring ever so delicately."
    "He presents the cup back to you, a perfect rosetta on top."
    emi "Wow, that looks amazing! The latte art is really nice."
    ingram "Comes with practice."
    "When you taste the drink again, the bitterness is now complimented by the mellow taste of creamy vanilla."
    emi "Mm! That's much better, thank you."
    "As you sip the latte, you stare at Ingram putting away the rest of the ingredients."
    emi "So wait, you're a barista then? I thought you were a guide of some sorts?"
    ingram "Well, both answers would be right technically."
    "He pulls out a sponge cake, along with a small cutting board and fresh carton of strawberries."
    ingram "There's a lot that goes into managing this place."
    ingram "Most of the time, I'm behind the counter being a barista."
    "His hands move quickly. In a flash, the strawberries are rinsed and sliced up."
    ingram "Though once in a while, I'll dabble in being a baker."
    ingram "I'm no expert by any means, but a little practice goes a long way."
    "He spreads a thick layer of cream over the cake, smoothing it with an icing knife."
    "Once the cake is iced, he delicately arranges the strawberries on top."
    "In just a few moments, a beautiful dessert takes shape before your eyes."
    ingram "But what you see is just part of the picture."
    ingram "My real job is spirit guiding—helping people move on."
    emi "Spirit guiding... you mentioned that earlier."
    emi "What exactly does that mean?"
    "Ingram explains that spirit guiding is the process of giving people one last happy memory before they move onto the afterlife."
    "Whether they use that chance to relive a happy memory or fix a regret they've held their whole life is up to them."
    "As a spirit guide, he simply provides them the opportunity and helps them through the process."
    "You think the concept makes sense, but ask him about how it all happens."
    "Before he can answer, the soft chime of the front bell cuts through the air."
    "A man stands by the doorway, glancing around with visible confusion."
    uk_generic "...Huh? Where... am I?"
    ingram "...Sorry, let me handle this."
    ingram "You said you wanted to know about spirit guiding. So why don't you see for yourself?"
    emi "Huh?"
    "Ingram turns to the man, his expression softening instantly. He walks towards him with calm, welcoming steps."
    ingram "Welcome to Nobaros Cafe."
    "The man blinks, clearly unsure how to respond."
    uk_generic "Nobaros...? I... I don’t remember coming here."
    ingram "That’s all right. You’re safe here. Please, have a seat."
    "Still looking uncertain, the man lets himself be guided to one of the counter stools."
    "Ingram moves with a quiet confidence, setting a menu before him."
    ingram "Here's our special drink menu. Feel free to pick whatever stands out to you."
    ingram "The drink you choose will reflect what your heart’s looking for."
    "Ingram returns behind the counter. You lean in, keeping your voice low."
    emi "So that man... is he a spirit? Or did he...?"
    "He nods, confirming your train of thought."
    ingram "Yes, he's passed on and will need spirit guiding."
    emi "How do you know?"
    ingram "Notice how disoriented he looks. He isn't really familiar with this place."
    emi "Couldn't he be a new spirit? Like the ones that are born after someone passes on?"
    ingram "Typically, new spirits are eager and enamoured by their surroundings."
    ingram "But not him. He's much too tense."
    "You understand what Ingram is getting at."
    "Out of the corner of your eye, you see the man rub his arm as he studies the menu."
    "You wonder why he's reading the menu so intensely."
    "Ingram seems to notice you getting antsy, and offers you a copy as well."
    "{color=#8489ff}Show a picture of the actual menu here for the player to read{/color}"
    ingram "This is a spirit guiding menu. It's different from the one used to serve regular customers."
    ingram "As you can see, each drink is associated with a specific type of memory."
    ingram "Depending on what the customer chooses, the spirit guiding process is tailored to their memory accordingly."
    "Just then, the man calls out to Ingram, wanting to order a latte."
    "{color=#8489ff}From the menu: Cafe Latte, A cup for those who carry remorse.{/color}"
    "{color=#8489ff}Smooth and steady as dawn, this latte draws forth the bitter moment your heart wishes it could change. Its warmth invites you to face that regret once more. Not to suffer, but to understand and find peace.{/color}"
    "Witout skipping a beat, Ingram begins preparing the drink."
    "Each step is deliberate—the sound of beans grinding, the hiss of steam, the gentle pour of milk into a ceramic cup."
    "{color=#8489ff}Show a picture of a small vial filled with Lunaria essence{/color}"
    "Then, he reaches for a small vial filled with a faintly glowing liquid. The light inside emits a soft aura, like liquid moonlight."
    "He tilts the vial, letting a few drops fall into the cup. The surface of the drink shimmers faintly, catching a soft glow as the essence dissolves."
    emi "What was that?"
    ingram "Essence from a Lunaria flower. It reacts to the truth in a person’s heart and helps bring their desired memory to the surface."
    "He slides the cup gently toward the man."
    ingram "Here you go. Take a sip, and tell me what it reminds you of."
    "The man wraps his hands around the cup, warmth spreading through his fingers as he brings it to his lips."
    uk_generic "...It tastes like... coffee from my kitchen. My wife used to brew it every morning."
    ingram "That sounds lovely. What was it like—those mornings with her?"
    "A small smile tugs at the man’s lips."
    uk_generic "Peaceful. She’d hum while she cooked, and I’d read the paper. It wasn’t anything special, but... it felt like home."
    ingram "I can imagine. It must've been pleasant having that sort of idyllic life."
    ingram "When was the last time you shared a morning like that?"
    "The man’s smile falters slightly."
    uk_generic "...Too long ago now."
    uk_generic "At one point, we were going through a divorce. A messy one."
    uk_generic "She and I got into an argument. And I said something I shouldn't have."
    uk_generic "Before I was able to apologize, she..."
    "The man chokes up."
    uk_generic "...There was an accident."
    uk_generic "...I haven't drank coffee ever since. I thought I’d forgotten the smell of it."
    "Ingram’s voice softens even more, his tone both steady and compassionate."
    ingram "Then you’ve remembered something precious. Hold onto it, just for a while."
    "The man closes his eyes and recollects himself."
    ingram "...Would you like to speak to her once more?"
    "The man looks up in surprise."
    uk_generic "What do you mean?"
    ingram "I can help you revisit that memory. See her again, and say what was left unsaid."
    "The man hesitates, then nods slowly."
    ingram "Come then, follow me."
    scene blank with bgwipe
    return