label sweven_mirror_intro:
    scene sweven_mirror with bgwipe
    show ingram with dissolve
    "Ingram leads the both of you to the back of the cafe."
    "As soon as he opens the door, a warm breeze flows past you."
    "A tranquil grove welcomes you in, and you immediately feel at peace."
    ingram "This is the center of Nobaros. Watch your step."
    "Ingram leads you down a forest path."
    "Soon, you find yourselves in front of what looks like a mirror. Its surface pulses faintly with light."
    "Here, the warmth is most prominent. Almost as if the mirror is alive."
    ingram "This is the Sweven Mirror. Here, you'll be able to see your wife again."
    ingram "You'll just need to enter the mirror, and I will guide you through the rest."
    uk_generic "...I want to see her. Just once more."
    ingram "If your heart is ready, the mirror will open the path."
    "The man nods, confirming his decision."
    ingram "Then let's begin."
    hide ingram with dissolve
    "Ingram gestures you to step back."
    "You watch as the man approaches the mirror, its light growing more intense with each step."
    "Ingram instructs the man to focus on his wife's memory while keeping his heart open."
    "The man takes a step into the mirror, causing ripples that disrupt his reflection."
    "Within moments, he disappears entirely into the mirror’s light, and the ripples soon become still."
    show ingram with dissolve
    "Ingram steps up to the mirror and places a hand on its surface, closing his eyes to concentrate."
    "He murmurs something, and the mirror shines bright once more."
    ingram "I hope you find your happiness."
    hide ingram with dissolve
    scene blank with bgwipe
    scene sweven_mirror with bgwipe
    "After what feels like an eternity, the glow finally starts to fade."
    show ingram with dissolve
    ingram "...May you rest in peace."
    "Ingram returns to your side, his eyes a more intense blue than before."
    ingram "...it's done. He's moved on now."
    emi "I don't understand. What was that all about...?"
    "Ingram explains that they have just witnessed the core part of the spirit guiding process."
    "After offering a drink & getting to know a little bit about the customer, he brings them to the Sweven Mirror."
    "With the Lunaria essence inside the customer, the Sweven Mirror creates a dream from their chosen memory."
    "He, as a spirit guide, helps them navigate the dream."
    "But at the end of the day, this memory is theirs, not his. He cannot always guarantee a good outcome."
    "Once the memory is over, the customer passes on to the afterlife, regardless of the outcome."
    "And thus, a new spirit will be born somewhere in the town of Nobaros."
    "You ask if the man was able to meet his wife again."
    emi "Was he able to apologize like he wanted to?"
    "Ingram looks at the mirror."
    ingram "...Yeah."
    ingram "In the end, he was able to face his regret, understand it and find peace with himself."
    "He turns to you, a gentle look on his face."
    ingram "This is what I do. It is the core reason behind Nobaros' existence."
    ingram "Everyone has a story. They all have a beginning and ending, but what's written in between is up to them."
    ingram "Now you..."
    ingram "You're a vagabond with no memories. And you might struggle to remember everything."
    ingram "There's no telling how long the process takes, as it varies from person to person."
    "Ingram explains that to help with memory recovery, he usually encourages vagabonds to be part of the spirit guiding process."
    emi "So... you’re saying I can help with spirit guiding too?"
    ingram "If you wish. You could assist during the sessions—observe, maybe lend a hand when needed."
    ingram "Sometimes, seeing how others find closure helps vagabonds remember their own stories."
    emi "And if I decide I don’t want to anymore?"
    ingram "Then you stop. Simple as that. The choice is yours."
    "His tone is firm, but not unkind. You sense that he means it—that he doesn’t want you to feel obligated."
    emi "Then... I want to try. If I can help people smile like that man did earlier, I’d like to be part of it."
    "You suddenly recall the scene of Ingram making coffee & icing the cake."
    emi "And maybe... I could help with the cafe too? While I’m here?"
    "Ingram looks at you, brows slightly raised. It’s clear the suggestion catches him off guard."
    ingram "...You want to work at the cafe?"
    emi "Yes, I do."
    emi "The way you made that man smile with a single drink & conversation... I’d like to help keep that feeling."
    ingram "You don’t have to. This isn’t your burden."
    emi "It wouldn’t be a burden! I just... want to be useful."
    "Ingram’s expression shifts. There's a flicker of conflict behind his eyes."
    "He crosses his arms, as though retreating behind habit."
    "There’s a long pause. Ingram’s gaze drops to the ground, his tone quiet but edged with hesitation."
    # TODO: replace emi's name with player chosen name
    ingram "…You don’t need to earn your place here, Emi."
    "He says it gently, yet firmly."
    emi "I know... but it feels right to do something while I'm here."
    ingram "You..."
    "You stare at him with determination, hoping to convey your sincerity."
    "He stares at you, a million emotions running through his face."
    "Finally, his shoulders ease just slightly."
    ingram "...All right. If it’s truly what you want, you can help around the cafe."
    ingram "I’ll show you how things work when there’s time."
    "He glances away, his voice softening almost to a murmur."
    "You smile, feeling a joy spark in your chest."
    emi "Then it’s settled!"
    "You hold out your pinky finger to him."
    emi "I’ll do my best, it's a promise!"
    ingram "Promise..."
    "Although he hesitates at first, he links his pinky with yours."
    ingram "...I'll make sure to help you out."
    return