label midnight_snack:
    emi "(You know what, let's just drink some water and head right to bed afterwards.)"
    narrator "I pull the water jug out of the fridge and pour myself a glass, taking a big gulp of the icy cold liquid."
    narrator "As I finish my glass, I savour the refreshing cooling sensation in my stomach."
    emi "(Ah, that hits the spot. I guess you can never go wrong with plain old water.)"
    show kai with dissolve
    narrator "Just then, Kai descends down the stairs and walks through the common area. He looks behind him to see if anybody is around, before taking careful steps into the kitchen."
    emi "Kai? What are you doing here?"
    kai "HYAHH!!"
    narrator "Right as Kai makes eye contact with me, he silently screams from shock, his voice hoarse and strained so as to not disturb the peaceful night atmosphere around the house."
    emi "Geez, you don't have to look so surprised. It's just me."
    kai "S-sorry, I didn't notice you. I wasn't expecting anybody to be downstairs."
    emi "I was here the whole time. . .and why are you speaking so quietly? What are you being all sneaky for?"
    kai "I was hungry. Thought I'd look around the kitchen and whip something up, but I'm a little scared of being nagged for cooking this late."
    emi "What? But you ate so much during dinner, how are you not full?"
    narrator "Kai's stomach gurgles as he nervously laughs, rubbing the back of his neck."
    kai "Well, it is what it is. You heard my stomach."
    kai "Oh, speaking of which, how'd you like dinner? I know you said it tasted good, but I wanted to hear the full review from the guest of honour."
    emi "Guest of honour? You think too highly of me, haha."
    emi "*Ahem*. . .well, I thought it was superb. There was an acceptable amount of sauce and the beef slices were exquisitely tender."
    emi "I was particularly impressed by how each little vegetable piece was well seasoned. It was truly a magnificent dish."
    narrator "As I describe my culinary experience with the haughtiest food critic voice I could muster, Kai's eyes glitter with enthusiasm. At the end of my review, the both of us burst out laughing."
    kai "Haha, you make a good food critic impression! You could totally get into a career in acting."
    emi "Oh, stop pulling my leg! Really though, I appreciate that you guys were willing to get together and cook for me."
    emi "If anything, I'm just sad that it was all finished before I could take seconds. I'd love to have more."
    kai "Oh, then you're in for a treat! Since I'm going to be cooking anyways, why don't I make a portion for you too?"
    emi "Huh? N-no, I think I'm fine. I shouldn't be eating this soon before bed. . ."
    narrator "The nikujaga from earlier flashes through my mind, and I start salivating."
    narrator "Against all odds, my stomach grumbles at the thought of eating more delicious food, betraying my own attempt to not indulge."
    emi "(Dang it, why did my stomach have to give me away?! I blame food for tasting so good.)"
    narrator "I feel a faint heat creep into my cheeks as Kai laughs, wiping a tear from his eye."
    kai "Hahaha, it looks like your stomach doesn't agree with you!"
    emi "Urgh. . .what are you going to make?"
    kai "Hmm, I'll figure something out! Just sit here and hang tight. I've got you covered."
    narrator "Kai sits me down at the dining table as he begins digging through the fridge for ingredients."
    narrator "His movements are natural and fluid, and he doesn't skip a beat in pulling out both a frying pan and a cutting board."
    narrator "He takes one of the aprons hanging off the wall and ties it onto himself in seconds, proceeding to wash his hands and start cutting up tomatoes afterwards."
    narrator "I can't help but stare more attentively than earlier, now that it's only him cooking."
    narrator "It's a bit jarring to see him so focused, considering how all over the place he normally is."
    emi "(I didn't expect him to know his way around the kitchen.)"
    emi "(Does he actually cook often? But I thought Ingram was the one who usually cooks here.)"
    kai "What's on your mind, Emi? You kind of have an intense look on your face."
    emi "Eh? Oh, no, don't mind me. I was just thinking about how you seem to really know what you're doing. Are you in the kitchen often?"
    kai "Hmm, once in a while, I guess?"
    kai "I don't find cooking too hard honestly. You just gotta be confident in your actions and know how to protect yourself."
    emi "You make it sound so easy, compared to Annelise earlier. . ."
    kai "Uh. . .let's not think about that. She's got spirit at least."
    kai "You might want to cover your ears. This could get a bit noisy."
    narrator "Kai throws the tomatoes into the frying pan, and a loud searing noise erupts from the heat."
    narrator "Almost immediately, he throws in a bunch of seasonings and starts stir-frying in a fast-paced manner."
    narrator "I watch in awe as he cooks the rest of the ingredients. Although he's just cooking, his movements are flashy, almost as if he's performing right in front of my eyes."
    emi "(I can't wait to see what he makes. . .)"
    scene blank with bgwipe
    scene kitchen_night with bgwipe
    show kai with dissolve
    narrator "After some time, Kai wraps up in the kitchen and approaches the dining table with a steaming hot dish."
    kai "Bon appetite, I made an egg and tomato stir-fry!"
    narrator "As he sets down the dish, I'm captivated by the sight of it. Fresh, ripe tomato pieces intertwine with velvety scrambled eggs, all enveloped in a glistening sauce."
    narrator "As I marvel at how visually pleasing everything looks, the rich, savoury aroma from the dish makes my taste buds tremble with anticipation."
    narrator "Kai hands me a pair of chopsticks as he takes the seat across from me, setting down a bowl of rice and cooked sausages for himself."
    kai "I hope you don't mind, but I gave myself some extra rice and sausages to fill my stomach a bit more."
    emi "Oh no, it's fine! This is perfect, actually. I'm blown away by how good this looks for just eggs and tomatoes."
    kai "Hehe, I appreciate the compliment. Go ahead and have a bite!"
    narrator "With chopsticks in hand, I extend my arm, grabbing a small piece of tomato and egg in one. As I pop it into my mouth, I dance in delight from the explosion of umami."
    narrator "Although simple, the acidity of the tomatoes melds together with the savouriness of the eggs, coming together to create a wonderful mouthfeel that leaves me satisfied."
    kai "So what do you think? Do you like it?"
    narrator "I nod excitedly as I happily take another bite, earning a prideful grin from Kai."
    narrator "Pleased by my reaction, he takes his chopsticks and digs into the dish himself, joining me in eating."
    emi "I'm surprised! I didn't think you could make such a nice dish with just eggs and tomatoes."
    kai "Yeah, right? It's ridiculously simple, so it's a really good and easy dish to make if you're ever looking for something to eat."
    kai "I also tried to make something light and healthy since you were worried about eating so close to bedtime. This way, it shouldn't be as bad on your stomach."
    emi "Oh, really? I didn't expect you to be so considerate. I mean, you were originally just going to make something for yourself, weren't you?"
    kai "Haha yeah, at first, I was. But I am the one who dragged you into joining me, so I might as well make it so that the both of us can enjoy ourselves."
    narrator "Hearing Kai's words brings a heartwarming smile to my face, touched by his actions."
    emi "(He's unexpectedly thoughtful. I thought he'd be the kind of person to just do whatever he feels without regarding other people.)"
    emi "(Well, he seems to be enjoying the food as much as I am. It feels pretty comfy chatting with him.)"
    kai "Hey Emi, you seem to like food a lot. What's your favourite thing to eat?"
    emi "Oh gosh, that's a hard question. There's so many good options to choose from!"
    kai "Haha, I feel you! When you like everything, how can you make a choice right?"
    kai "Let me rephrase the question a bit then. What food would you never refuse if it was offered?"
    emi "Okay, if it was offered to me, then it'd have to be any dessert! I can never resist anything containing sugar, even if it kills me."
    kai "Oh, so you're a fellow sweet tooth like me then!"
    emi "Hey, don't compare me to you. At least I like strawberries, they're the best in cakes!"
    kai "It's not my fault I get stomachaches whenever I eat strawberries!"
    kai "Besides, it's only fresh strawberries that give me a problem. Strawberry flavoured things are okay."
    emi "How does that work?!"
    kai "I don't know, ask my body! It just does what it does."
    narrator "The both of us bicker cheerfully as we finish the rest of the meal, discussing all sorts of topics related to desserts."
    narrator "Before long, we wrap up and decide to head up to our rooms to retire for the night."
    scene blank with bgwipe
    scene yuugen_common with bgwipe
    show kai with dissolve
    emi "Thanks for cooking, Kai. That tasted pretty good."
    kai "Yeah, no problem! Thanks for joining me, we should go check out some of the other food places around here sometime."
    emi "That sounds fun, I'd be down to! Have a good sleep."
    kai "You too, good night!"
    return
