label strawberry_tart:
    narrator base "I carefully place the strawberry tart into a mini box, ensuring it's secure before sealing it shut with tape. With the box in hand, I head back to the cafe entrance."
    scene blank with bgwipe
    scene cafe with bgwipe
    emi base "(Huh? Where'd he go? I thought I told him to wait here.)"
    narrator "I scan the cafe, searching for any sign of Kai."
    emi talk "Ah!" with talkpunch
    narrator base "Suddenly, a pair of hands slam down on my shoulders, causing me to gasp and almost drop the box."
    show kai with dissolve
    narrator "Kai bursts into laughter, clearly amused by his prank."
    kai "Gotcha, Emi! Sorry, I couldn't resist."
    narrator "Turning to face him, I try to hide my surprise with a glare."
    emi talk "Kai, you scared me!"
    kai base "Aw, come on, it was just a little joke."
    narrator "He wipes a tear from his eye, looking at me with a sheepish smile."
    emi talk "It isn't very nice to scare someone who went through the trouble of finding food for you."
    kai base "You're right, I'm sorry. I promise I'll behave."
    kai "So what did you end up finding?"
    narrator "With a huff, I push the box containing the strawberry tart into his arms."
    emi talk "There was a leftover strawberry tart. It probably won't fill you up too much, but it was what we had."
    narrator base "Kai carefully opens the box, peering inside to inspect the strawberry tart. For a brief moment, his face contorts, but he quickly covers it with a polite smile."
    kai "Oh, thanks! I, uh, appreciate that you took the time and effort to find something for me."
    emi talk "Is something wrong? You don't look very happy."
    emi base "(I don't think the tart looked that bad, did it. . .?)"
    narrator "Kai averts his gaze, unable to look me in the eye. He hesitates to answer."
    kai "The truth is, I'm not a very big fan of strawberries. They just don't sit well with my stomach for some reason."
    emi talk "Oh shoot, I'm so sorry! I should've asked you if you had any preferences. I can go grab you something else!"
    kai base "No, don't worry about it! I can still eat it. I'll just make sure to eat a big meal when I get home later."
    emi talk "Are you sure? You don't have to force yourself."
    kai base "Really, it's okay. Don't feel too bad, you didn't know any better."
    narrator "Despite my insistence, Kai refuses to accept anything else and makes do with the strawberry tart."
    narrator "To prove his point, he take the tart and bites out of it."
    emi talk "W-wait, you don't have to-!"
    narrator base "In a matter of minutes, he scarfs down the strawberry tart, leaving no crumb behind."
    narrator "He forces a smile and shows me a thumbs up in an attempt to prove that he's fine, but the expression on his face says otherwise."
    kai ". . .mmph!"
    emi "(!!!)"
    emi "(Oh no! It's stuck in his chest!)"
    narrator "Panicked, I quickly run to the counter, filling a glass with water to help Kai wash down the food."
    narrator "With some effort, he manages to get the food down."
    kai "*Huff {w=0.2}huff*"
    kai "Thanks. . .I needed that."
    kai "I don't feel so good. . .I think I should go home and rest."
    emi talk "I'm so sorry. I hope you feel better soon. . ."
    kai base "Thanks for the help Emi. I'll see you later."
    narrator "I watch Kai stagger out of the cafe, the door chime tinkling as he leaves, my heart heavy with guilt."
    hide kai with dissolve
    emi "(Dang it, I should've chosen the macarons!)"
    emi "(Next time, I'll make sure to ask about dietary preferences instead of assuming.)"
    emi "(Let's get onto the next chore. . .)"
    return
